### ISSUE TITLE
我在安卓设备上跑LUA。用的windows上的vscode写代码。可以调试吗?

### ISSUE THREAD

**Issue by sd3970566** [actboy168/lua-debug#101]
我在安卓设备上跑LUA。用的windows上的vscode写代码。可以调试吗?

**Comment by actboy168** [comment]
ios上可以，但我没有试过android。部分问题可以你需要你自己解决，同时也欢迎你提供pr。

你需要解决两个问题
1.让remotedebug在android上编译通过。
2.让windows和android可以相互通信，通过adb，代理或者路由器。

**Comment by actboy168** [comment]
已经支持android

**Comment by nkligang** [comment]
> 已经支持android

请问具体怎么做的呢
