### ISSUE TITLE
Launching debugger hits breakpoints as normal, but shows no visual indication

### ISSUE THREAD

**Issue by bleachkitty** [actboy168/lua-debug#102]
Whenever I hit a breakpoint, I get no visual indication of hitting that breakpoint except that it places my cursor on the appropriate line.  The callstack, variables, and everything else works as intended, but there's no indication in the code itself (no yellow highlight or anything).

This is a screenshot of me at a breakpoint:

![no_indication](https://user-images.githubusercontent.com/13199436/88624009-0e601280-d05b-11ea-82c8-83cad6e3cfad.png)

Here is my configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Journey x86 Debug",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": false,
            "stopOnThreadEntry": false,
            "runtimeExecutable": "${workspaceFolder}/bin/x86/JourneyD.exe",
            "cwd": "${workspaceFolder}/bin/x86",
            "consoleCoding": "utf8",
            "luaVersion": "5.3",
            "luaArch": "x86",
        }
    ]
}
```

**Comment by actboy168** [comment]
It may be because your chunkname does not meet the Lua standard.

**Comment by bleachkitty** [comment]
Thank you for getting back to me.

As far as I can tell, my chunkname is correct.  On the C++ side, I'm using luaL_loadfile() and the path should be fine.  Here's an example of the parameter being passed to it:

![image](https://user-images.githubusercontent.com/13199436/89581823-83b2ac80-d7ec-11ea-8ce0-d556d3794ff5.png)

Note that this worked several months ago when I last was working on the Lua side of this project, so something either changed with VS Code or with this plugin.  I did revert this plugin back several versions and it didn't work, so I'm guessing it's something that changed in VS Code.  I also found this:
https://github.com/microsoft/vscode/issues/68616

That post is about Node.js, but it's pretty much the same issue I'm experiencing.  This implies something changed in their debug API.

Any ideas?

**Comment by actboy168** [comment]
1. Find the installation directory of the extension. e.g. `%USERPROFILE%\.vscode\extensions\actboy168.lua-debug-1.25.5`
2. Open this comment [script/frontend/main.lua#L25](https://github.com/actboy168/lua-debug/blob/master/extension/script/frontend/main.lua#L25)
3. Run again, you can find the log file `client.log` in the extension directory.
4. Please send me the log.

**Comment by bleachkitty** [comment]
Here you go.
[client.log](https://github.com/actboy168/lua-debug/files/5044528/client.log)

**Comment by actboy168** [comment]
According to the log, lua-debug tells VSCode to pause at `C:/bob/proj/dev/dl/Journey/bin/Data/global/Scripts/Core/ScriptApp.lua`, is this a correct path?

**Comment by bleachkitty** [comment]
YES!  That was it!  I really wish Windows was case sensitive like the rest of the world.  Anyway, I changed the case of the chunkname and it works.

![image](https://user-images.githubusercontent.com/13199436/89838511-49187f00-db20-11ea-8ea8-48a500a82a98.png)

Thank you so much for looking into this!!

**Comment by stax76** [comment]
I'm having this issue with the mpv media player.

[client.log](https://github.com/actboy168/lua-debug/files/8322446/client.log)

**Comment by actboy168** [comment]
@stax76  Please open a new issue.

**Comment by stax76** [comment]
OK, when I do, I will provide much more details.
