### ISSUE TITLE
debugging 5.4 lua code  crashed  in 1.25.5 and later versions

### ISSUE THREAD

**Issue by baekhyunee7** [actboy168/lua-debug#103]

**Comment by actboy168** [comment]
You need to use the latest lua source code.

**Comment by baekhyunee7** [comment]
attach模式下，debug链接了luadll的exe文件，lua是最新的源码，还是会crash

**Comment by 6spring** [comment]
似乎是有些问题，使用最新lua.org下载的编译的dll会crash，如果换用lua debuger 的runtime\win64\lua54\lua54.dll 正常，用 bin\win\lua54.dll也会crash
