### ISSUE TITLE
Debugging with "runtimeExecutable" only working once

### ISSUE THREAD

**Issue by MariusBe97** [actboy168/lua-debug#107]
Lua-Version: 5.4.1

Steps to reproduce:
- Run lua code with c++/lua api
- Execute debugger with "runtimeExecutable"
- Breakpoints are triggered only once
- Debugging is working up to version 1.27.0

**Comment by actboy168** [comment]
Can you provide an example?

**Comment by MariusBe97** [comment]
It's fixed with version 1.29.1.
