### ISSUE TITLE
SSH-Remote compatibility

### ISSUE THREAD

**Issue by rlnilsen** [actboy168/lua-debug#110]
I'm trying to run the following test script on a remote Ubuntu ~16.04~ 18.04 PC via the VS Code SSH-Remote extension.
```
print 'hello'
assert(io.open("testar", "w")):close()
```
No output or messages of any kind show up. No file `testar` is created on the remote PC.

Is this supposed to work?

The SSH connection is working as I can browse and edit files on the remote PC through VS Code.

I installed lua-debug on the remote PC via the Extensions view in VS Code:
```
root@vmserver:~# ls .vscode-server/extensions/
actboy168.lua-debug-1.29.1
```

Running the same script locally works fine; 'hello' is shown in the `OUTPUT` tab and the file `testar` is created.

The local machine with VS Code is running Windows 10 1909 x64.

**Comment by actboy168** [comment]
You need to compile lua-debug on the remote server yourself.

**Comment by rlnilsen** [comment]
That worked, thank you very much!

For the record, I misspoke earlier, the remote PC runs Ubuntu 18.04 (not 16.04).
