### ISSUE TITLE
支持busted的debug吗

### ISSUE THREAD

**Issue by ZhouJiaZhi** [actboy168/lua-debug#111]
我使用busted写了个单元测试，我在单元测试第一行加了require 'busted.runner'()，我通过lua test.lua是可以直接运行这个单元测试的，但是我使用lua-debug里面的run和debug功能会提示module 'busted.runner' not found:
https://github.com/Olivine-Labs/busted

**Comment by actboy168** [comment]
找不到模块，显然是没有设置对package.path/capth

**Comment by ZhouJiaZhi** [comment]
@actboy168 
我不知道怎么正确设置这个，我通过code runner是可以直接跑的，你可以本地试着设置一下吗

**Comment by actboy168** [comment]
你可以看看lua的文档
