### ISSUE TITLE
现在支持mac下使用吗

### ISSUE THREAD

**Issue by ZhouJiaZhi** [actboy168/lua-debug#112]
搜了下历史的issue发现是2018年不支持mac使用，现在支持了吗？
插件描述里面包括了macos，但是我执行的时候他提示runtimeExecutable不支持
<img width="335" alt="截屏2020-12-06 09 46 28" src="https://user-images.githubusercontent.com/20750357/101269243-eb333580-37a7-11eb-9143-40a1af65953c.png">
<img width="274" alt="截屏2020-12-06 09 47 17" src="https://user-images.githubusercontent.com/20750357/101269254-08680400-37a8-11eb-90e0-b7ec2a557a79.png">

**Comment by actboy168** [comment]
只是不支持runtimeExecutable
