### ISSUE TITLE
vscode最新版1.18.1debug报错

### ISSUE THREAD

**Issue by Daily1116** [actboy168/lua-debug#12]
项目工程：lua_workspace/test.lua 
launch.json配置：
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/test.lua",
            "cwd": "${workspaceRoot}",
            "path": "${workspaceRoot}/?.lua",
            "cpath": "${workspaceRoot}/?.dll",
            "arg": [],
            "console": "utf8"
        },
        {
            "name": "attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "ip": "localhost",
            "port": 4278,
            "sourceMaps": [
                [
                    "./",
                    "${workspaceRoot}"
                ]
            ]
        }
    ]
}

debug 报错，提示：spawn EACCES，帮看下，是我配置弄错了还是什么原因，谢谢！

**Comment by Yan47** [comment]
So am I !

**Comment by Liguangxin1989** [comment]
me too !   vscode 是1.19.1，麻烦帮忙解决一下，多谢啦

**Comment by Ericzh2017** [comment]
vscode1.16.1也报错。。。 spawn EACCES
