### ISSUE TITLE
mac attach 模式无响应

### ISSUE THREAD

**Issue by cloudfreexiao** [actboy168/lua-debug#125]
根据如下issue  尝试在 mac 系统下 attach 模式 调试 最新 skynet 发现没有任何响应
https://github.com/actboy168/lua-debug/issues/113 
https://github.com/actboy168/lua-debug/issues/112

配置如下
```lua
    "configurations": [
        {
            "name": "skynet",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "processId": "10144",
        }
    ]
```
运行 命令
```lua
 ./skynet examples/config
```
启动 服务
```lua
testdeadloop 
```
请问一下 我的配置哪里有问题呢

**Comment by actboy168** [comment]
processId支持windows。

配置可以参考 https://github.com/actboy168/lua-debug/tree/master/examples/attach

**Comment by cloudfreexiao** [comment]
试了下 能用了 谢谢！
