### ISSUE TITLE
使用xpcall debug时，执行xpcall报错，会造成进程crash

### ISSUE THREAD

**Issue by zh844874696** [actboy168/lua-debug#130]
这是我的测试代码
local s = {}
local results = xpcall(s["a"], function(e) print("sf") end, {12})

请问，是需要怎么配置才能不造成进程crash。

**Comment by actboy168** [comment]
我无法重现

**Comment by zh844874696** [comment]
已经找到问题了， 需要关闭vscode断点下的Caught Errors By Native和Uncaught Errors 这2个选项
