### ISSUE TITLE
print(package.path) != %LUA_PATH% ( 1.38.0 on Win10, 64bit )

### ISSUE THREAD

**Issue by hemmerling** [actboy168/lua-debug#136]
When executing a LUA script.
`print(package.path) `
should print the contents of the environment variable LUA_PATH. On Win10pro, 64-bit, this should be - on my Win10 system, my choice for LUA_PATH -
`./;.\?.lua;.\?\init.lua;C:\Users\Administrator\AppData\Roaming\luarocks\share\lua\5.3\?.lua;C:\Users\Administrator\AppData\Roaming\luarocks\share\lua\5.3\?\init.lua;`
By this, the LUA script may process 
`require("module")`
statements, both of local modules and of modules installed by LuaRocks.
This is true on my computer when running LUA scripts by POWERSHELL or CMD shell, or if I use some other VSC LUA debugger plugins.
( Some other VSC LUA debuggers add some extra string data to this string, by this a LUA script may find out that it is running in VSC and not in a shell.. ).

****************
Indeed, VisualStudioCode with "lua-debug 1.38.0" prints the LUA style path to the current working directory, with "/?.lua" added.
Example:
`C:\Users\Administrator\MyLuaWorkingDirectory/?.lua`
, while executing the LUA script 
`C:\Users\Administrator\MyLuaWorkingDirectory/test.lua`

ISSUE:
By this,  VisualStudioCode with "lua-debug 1.38.0" fails to process
`require("module")`
statements, if the module was installed by LuaRocks.
****************

Just by special trick to add
`./;`
to the LUA_PATH string,
I am able to process
`require("module")`
statements, if the module is a local module, situated in the LUA working directory where the LUA script is situated which "requires" a module. Please note that "/" and not "\" and neither "\\" is needed so that this trick works.

WORKAROUND, but no solution:
if I add the statement
`package.path = package.path .. ";C:\\Users\\Administrator\\AppData\\Roaming\\luarocks\\share\\lua\\5.3\\?.lua"`
to my code, 
`require("module")`
statements are processed properly also for modules installed by LuaRocks.

FIX NEEDED:
Please implement that
`print(package.path) `
prints the contents of the environment variable LUA_PATH

**Comment by actboy168** [comment]
Add `path` in launch.json, it can specify package.path.

**Comment by hemmerling** [comment]
1. Thanks for another workaround, might you specify a working example of launch.json?
2. But it would be great to fix this, without help of launch.json anyhow, ok ?! :-)

**Comment by actboy168** [comment]
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "debug",
            "program": "${workspaceFolder}/test.lua",
            "path": "${env:LUA_PATH}
        }
    ]
}
```

**Comment by hemmerling** [comment]
Thanks, it works!

But as using such launch.json files is not comfortable, please fix your code too, please.

**Comment by actboy168** [comment]
Nothing needs to be fixed, the design is just that.

**Comment by hemmerling** [comment]
On Windows, with LuaDebug 1.40.0, 
Your fix with "path" works by the VSC debug option "Debug (Script)".

With the JSON debugging configuration "Debug Current Script", this does not work.

**Comment by actboy168** [comment]
You can modify the default value of path in the settings.

**Comment by hemmerling** [comment]
THANKS alot, problem solved.

( I beg your pardon, I am newbie to VSC, especially for configuration with menu & launch.json )

**Comment by actboy168** [comment]
This is a feature of vscode.
https://code.visualstudio.com/docs/editor/variables-reference

**Comment by hemmerling** [comment]
Cool !
Thanks for the comprehensive answer :-)
