### ISSUE TITLE
error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hemmerling** [actboy168/lua-debug#137]
The plugin "lua-debug 1.38.0 does not work at all on VSC /  Debian Linux 10.7, 64bit-

When trying to run or debug a LUA script file, e.g. 
`/home/<user>/lua/test.lua`

( with <user> the default user with which you are logged in )

, it aborts operation by a VSC terminal window (!) message 
******************************
`cd /home/<user>/lua ; /home/<user>/.vscode/extensions/actboy168.lua-debug-1.39.0/runtime/linux/x86_64/lua53/lua -e "dofile[[/home/<user>/.vscode/extensions/actboy168.lua-debug-1.39.0/script/launch.lua]];DBG{9017}" /home/<user>/lua/test.lua 

/home/<user>/.vscode/extensions/actboy168.lua-debug-1.39.0/runtime/linux/x86_64/lua53/lua: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`
******************************
With the same Debian Linux 10.7 64-bit system, executing Lua files works fine both by Bourne shell and by VSC with some other LUA debugger plugins.

**Comment by actboy168** [comment]
I can't reproduce it.

**Comment by hemmerling** [comment]
Now with LuaDebug 1.40.0, with Debian Linux 10.7,
again total failure, looks like same error.

The TERMINAL output of VSC:

>  cd /home/node8/lua ; /home/node8/.vscode/extensions/actboy168.lua-debug-1.40.0/runtime/linux/x86_64/lua53/lua -e "dofile[[/home/node8/.vscode/extensions/actboy168.lua-debug-1.40.0/script/launch.lua]];DBG{9257}" /home/node8/lua/run_my_first_module.lua 
/home/node8/.vscode/extensions/actboy168.lua-debug-1.40.0/runtime/linux/x86_64/lua53/lua: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

**Comment by actboy168** [comment]
Same as #138
