### ISSUE TITLE
The debugger does not work with a version of Lua that is not equal to 5.4

### ISSUE THREAD

**Issue by serg3295** [actboy168/lua-debug#138]
The debugger starts, but hangs waiting if the parameter "lua. debug.settings.luaVersion" differs from 5.4 or latest.
I can only exit the debugger by pressing Shift-F5 twice with the message "Timeout after 2000 ms for 'terminate' "

If version 5.4 or latest the debugger is working fine.

Kernel: 5.4.0-77-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.24.0
wm: marco dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal

![err1](https://user-images.githubusercontent.com/75196080/123791733-7745af80-d8e8-11eb-8cf2-49268cff4a13.png)

**Comment by actboy168** [comment]
Maybe your linux missing the readline. In fact, readline is not important to the debugger, so I have removed it.  e2432b32acb2764425c77f2af48b243e5cd40b59

**Comment by serg3295** [comment]
Is this library?
```
serg@Lenovo:~$ ldconfig -p | grep libreadline
	libreadline.so.8 (libc6,x86-64) => /lib/x86_64-linux-gnu/libreadline.so.8
	libreadline.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libreadline.so.5
	libreadline.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libreadline.so
serg@Lenovo:~$ 
```

**Comment by actboy168** [comment]
yes

**Comment by serg3295** [comment]
I have built version with commit  `e2432b3`. It  works correctly now for all Lua versions 5.1- 5.4. 
Thank you!
