### ISSUE TITLE
os.exit(0) is not processed properly

### ISSUE THREAD

**Issue by hemmerling** [actboy168/lua-debug#139]
The statement “os.exit()” is not processed properly, both on Windows and Linux.

- Version 1.40.0 does not work properly in “Run Without Debugging” mode: No debug console output.
- Version 1.40.0 works properly in “Start Debugging” mode, just if in the step mode. But if the button “Continue(F5)” is pressed, i.e. the debugger turns into “Run Without Debugging” mode, all debug console output is supressed .

This simple code makes reproducable effect, both on Linux and Windows.

> print(package.path)
print("Hello")
print(package.path)
print("Hello")
os.exit(0)

I also checked that the workspace directory is the directory where this script is located ( must not be important, but good to know ).

For comparison, another VSC Lua debugger 
http://marketplace.visualstudio.com/items?itemName=tomblind.local-lua-debugger-vscode
processes os.exit(0) always properly. 
But I need your debugger, as the "Lua Test Adapter" depends on it...

**Comment by actboy168** [comment]
You can use  `os.exit(0, true)`.

**Comment by hemmerling** [comment]
The problem is not 0 or true. Its not the return value.

The problem is, that all published standard code uses this
>result = <any number>
os.exit(result)
and I must modifiy this code to make it run in VSC.

Vice versa, if I publish code ( on GitHub..), if I publish my original code, I can´t follow the standard rules...

So I would be pleased about a fix, so that standard code runs properly within VSC and your debugger.

Btw, whats the reason for the os.exit() problem ?

**Comment by actboy168** [comment]
I don't think os.exit(0) is a standard usage. The second parameter of os.exit determines whether to call lua_close. A lua program can only exit correctly when it finally calls lua_close. Exit without lua_close is no different from crash.

**Comment by hemmerling** [comment]
exit()'s origin is from Unix, C:
https://man7.org/linux/man-pages/man3/exit.3.html

So there is just ONE parameter.
Any Unix shell knows these exit codes
This is even implemented in COMMAND / CMD / Powershell from MSDOS to Win10.

So a batch file ( the script running in a shell ) can react to the return codes.
0 = ok
1, 2,... = something is wrong.

As this is basic knowledge and common culture since 50 years ( since Unix & C started ), swapped to the PC with PC, later to Linux on PC, everybody is using an exit() with no or one parameter.

>  Exit without lua_close is no different from crash.

>os.exit()
os.exit(0)
os.exit(1)
no os.exit() at all
...

works fine both on Linux and Windows command line, with LUA script files.

So my LUA application which I ported from Linux / Windows to the CORE games platform ( which does not know about os.exit at all, as it is a sandbox LUA implementation ), is

http://www.github.com/bluebird75/luaunit

There are the following os.exit() statements in the core files

luaunit.lua

**Comment by actboy168** [comment]
a) b)
We are talking about os.exit in lua, not exit in c.
c)
Luaunit use os.exit is wrong. lua-debug also uses a fork of luaunit, which fixes os.exit.
https://github.com/actboy168/bee.lua/blob/3c6764ad21d20cf279aea3077e823363f045e854/test/test.lua#L59
d)
When you just want to exit and don't care about anything,  you don't need the second parameter. But you just want to exit decently, you need the second parameter.
e)
Unfortunately lua51's os.exit does not support safe exit, which is why lua later solved this problem.

**Comment by hemmerling** [comment]
a)
>We are talking about os.exit in lua, not exit in c.
Yes, standard is that Lua has ONE parameter for exit(), as with most other computer languages.
As Lua is often included in bare C/C++ applications,  and written in C/C++, it is in this tradition.

Most other known programming languages with shell application option for their applications offer an exit()  too, I don´t know any where a second parameter is implemented.
And as the OPTIONAL parameter of os.exit() is implemented recently, it can´t be that all given OpenSource Lua code must be modified....

b)
Well your plugin has to terminate a Lua session properly,
when the Lua code ends with

either nothing
os.exit()
os.exit(1) 

As such the code is written since 20 years of Lua, and for any other programming language since 50 years.

The shells don´t crash if Lua is terminated this way,
you crash the Lua process, with the effect that the output is consumed and not displayed.

VSC plugins don´t have to crash the applications they are debugging, if the application follow the standard rules.

c)
Luaunit is popular
https://www.google.com/search?q=lua+unittest
top #1 position.

It is one of 100s of Lua applications, which end by

os.exit()
os.exit(1)
no os.exit()

Why do you make your VSC plugin worthless, as I must comment "you must modify given OpenSource code heavily to let it run in this debugger ?

Why do you insist  - as VSC plugin developer - to urge developers of your target language Lua  for certain irrelevant code rules ?
Do you do Lua coding at all?
Did you debug given OpenSource Lua code in your own debugger?

d)
Thanks for pointing me to a fork of LuaUnit.
But its your fork, and its not even a fork.

As the title is
Lua runtime and toolset 
https://github.com/actboy168/bee.lua

its a complete new runtime?!
I don´t want another Lua runtime, nor patches for Lua runtime.

I even don´t see now a "fork",
as a fork would be a complete new GitHub project ( especially due to the non-MIT license of LuaUnit, it should not be mixed with standard MIT-licensed Lua code ),
or at least a sub-project, in a folder.
I don´t see anything of that.
You just pointed me to a "test page" of your GitHub account...

**Comment by actboy168** [comment]
I don't want to engage in such meaningless arguments anymore. You can use the solution I provide you, or find a solution by yourself.
