### ISSUE TITLE
"wait" profile does not open listening port

### ISSUE THREAD

**Issue by briandlucas** [actboy168/lua-debug#140]
i'm sure it is my setup but... "wait" debug profile does not open a listening port.  no errors or messages and VS appears to be running and waiting.  confirmed no listening port via "netstat -a".  have changed listenPublicly true/false and listenPort.  am able to connect to a different listening process on port 56789 locally and remotely.  also tried another VS debugger that is able to open/listen on a port.  VS v1.58.1, Win v10

**Comment by actboy168** [comment]
I don't understand what your problem is.

**Comment by briandlucas** [comment]
as i understand the process, the "wait" debug profile starts the extension and listens on port 56789 (default) for the debugee to connect and handshake.  while troubleshooting why the debugee fails to connect, i noted (via netstat) that the extension (or any other process) is not listening on port 56789.  in short, my install of the extension is not listening/waiting for the debugee client to connect.

**Comment by briandlucas** [comment]
removed and reinstalled extension - executed "wait" profile again but this time windows firewall asked to create rule.  allowed connection and now working.
