### ISSUE TITLE
Debugging script with lua_file_system call fails

### ISSUE THREAD

**Issue by serg3295** [actboy168/lua-debug#141]
I am trying to debug script containing `lfs.attributes()` call. Directory `./tstdir` is located in ${workspaceFolder}.
When I run this script with lua interpreter lfs.attributes() returns 'table' as expected. But under debugger it returns `nil` and error message 'cannot obtain information from file './tstdir': No such file or directory'.
Change `./tstdir` on `tstdir` gives the same result. 
What I'm doing wrong?

**To reproduce**
```lua
local lfs    = require'lfs'
local srcDir = './tstdir'

local test, errmsg, lvl = lfs.attributes(srcDir)
print(test, errmsg, lvl)
if test  then
-- if lfs.attributes(srcDir) then
  if lfs.attributes(srcDir).mode == "directory" then
    print('OK!')
  end
else
  error(string.format("Cannot open directory, %s", srcDir))
end

```
**Environment**
![err28](https://user-images.githubusercontent.com/75196080/126741968-a4b32762-cd4e-48bb-be75-09876788e931.png)

**Edit**
I have tested this script on Windows 10 with settings:
```json
{
  "lua.debug.settings.luaVersion": "5.1",
  "lua.debug.settings.luaArch": "x86",
}
```
All works correctly.
So, the problem is on linux only.

**Comment by actboy168** [comment]
I think this is a bug of lfs.

**Comment by serg3295** [comment]
Probably.
Thanks.

**Comment by serg3295** [comment]
As a workaround.
I did set absolute path instead of relative and make new test 
 `local srcDir = '/home/serg/temp/tstdir'`. 
In this case script works both in debugger and lua interpreter.
