### ISSUE TITLE
无法命中断点

### ISSUE THREAD

**Issue by car520120** [actboy168/lua-debug#142]
如果我直接启动程序后，设置 stopOnEntry = false 不生效
目前只能要断点 文件 a.lua 需要在C层先断点然后再附加过去，再启动C层才能命中a.lua中的函数
还有另一个特殊的，如果a.lua中所有函数都是全局的，则无法命中 要是能结合一下 vscode cpptools这个工具混合调试就好了

**Comment by actboy168** [comment]
看不懂你在说什么。

混合调试只需要其中一个使用launch模式，另一个使用attach模式即可。

**Comment by car520120** [comment]
我设置断点后，无法命中只有暂停才会进入lua代码中

**Comment by actboy168** [comment]
可能是调试器无法找到你的源文件，试着配置sourceMaps或者修改你源代码的chunkname。

**Comment by car520120** [comment]
能教我怎么调试你的源代码吗？可能是我的运行的目录不对的导致的！支持一下 xmake 这个编译工具可以吗？

**Comment by car520120** [comment]
能教我怎么调试你的源代码吗？可能是我的运行的目录不对的导致的！支持一下 xmake 这个编译工具可以吗？ 新手来的，请不要见怪，谢谢大佬

**Comment by actboy168** [comment]
没有支持多个构建工具的必要

**Comment by car520120** [comment]
你这个有架构说明文档的吗？给我一份好吗？我学习一 下

**Comment by actboy168** [comment]
没有
