### ISSUE TITLE
初始化阶段一些文件的断点无法被捕捉到

### ISSUE THREAD

**Issue by TTTTh** [actboy168/lua-debug#143]
我是用的是launch模式启动，指定了启动的.exe，但是在初始化阶段的几个文件中的断点都是捕捉不到的，即使是配置了stopOnEntry，也只会在memory阶段拿到入口的.lua文件的路径，F10或者F11也没办法往里走。
想知道这种情况普遍吗？有什么办法避免，或者找到原因吗？谢谢

**Comment by actboy168** [comment]
可能是调试器无法找到你的源文件，如果你使用了自己的loadfile/load，需要指定符合lua规范的chunkname

**Comment by car520120** [comment]
是的，我使用了 自己的 loadfile / load  我需要怎么改才可以用上这个，谢谢的了

**Comment by actboy168** [comment]
需要指定符合lua规范的chunkname,具体请看lua的文档。
