### ISSUE TITLE
Skip to the first defined breakpoint instead of stopping at the first line

### ISSUE THREAD

**Issue by adamnejm** [actboy168/lua-debug#145]
Currently when you run the debugger it will stop at the fist code line. This would be OK if no breakpoint were defined, but usually you just want to skip to the first breakpoint immediately, resulting in having to press the debug key twice *(continue debugger after starting)*.

Option *"skip to the first breakpoint at start"* or something along these lines would be the way.

**Comment by actboy168** [comment]
I think what you need is `"stopOnEntry": false`.

**Comment by adamnejm** [comment]
Oh yes, sorry. I didn't realize this was an option, thank you!
