### ISSUE TITLE
1.49.0扩展包好像在WSL ubuntu18.04 启动调试没得反应  

### ISSUE THREAD

**Issue by lualcs** [actboy168/lua-debug#151]
我应该如何找问题呢，调试窗口也没有任何输出  我另外一台电脑是可以调试的，但是是 ubuntu 20 ，

更新后用不起了，但是之前哪个版本是可以的-这个版本 重新安装(手动删除后) 也不管用

**Comment by actboy168** [comment]
1.49.1应该可以解决这个问题

**Comment by lualcs** [comment]
好了
