### ISSUE TITLE
Can't work in VSCode new version

### ISSUE THREAD

**Issue by Penggeor** [actboy168/lua-debug#152]
I was update my VSCode to 1.61.1 and then find the Lua Debug doesn't work.
My colleague suffers from the same problem. But him make it work by reinstall VSCode not over 1.16.1 version.
![image](https://user-images.githubusercontent.com/68799055/138243057-5ba4be0e-76f2-445b-8677-5448dbce4f10.png)

**Comment by Penggeor** [comment]
Re-install version not over 1.6 and

**Comment by jradxl** [comment]
Lua Language Server: 2.4.7
Lua Debug (this) : 1.50.1
are all working for me
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:18:44.904Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-20-generic
