### ISSUE TITLE
luajit branch

### ISSUE THREAD

**Issue by fesily** [actboy168/lua-debug#156]
我基于lua-debug修改了部分代码可以在luajit上运行,可以合并进来吗,或者另开一个branch也可以

**Comment by actboy168** [comment]
我很愿意合并luajit的支持。

**Comment by fesily** [comment]
目前在macos M1芯片上测试通过,但是在x64的windows和macos的未测试,我没有使用任何平台特有的api,应该不会导致平台兼容问题.但是我并没有像lua其他版本一样提供luajit本体程序.

**Comment by fesily** [comment]
#53 
#79

**Comment by fesily** [comment]
### BUG
1. 在某些条件下读取table信息不完整  ❌
2. 创建的coroutine信息不正确           ❌
3. 特定条件下断点无法命中❌
4. 特定条件下step over乱跳❌

**Comment by actboy168** [comment]
我已经合并了luajit分支。但是发布lua-debug涉及到交叉编译 (在x86_64的linux/macos编译arm64的版本)。luajit的构建流程会先编译buildvm，然后在构建环境执行buildvm。所以buildvm不应该被交叉编译。

我认为应该把buildvm的构建脚本单独抽离出来，然后交叉编译的构建流程变成
```
# 构建buildvm
luamake --buildtools
# 构建lua-debug
luamake --platform linux-arm64
```

**Comment by fesily** [comment]
应该行不通,buildvm强依赖LUAJIT_ARCH_*这个宏,等于说buildvm是根据平台环境来决定程序代码的.不能一次性编译一个工具然后直接交叉编译使用

**Comment by fesily** [comment]
我修复一下cl的问题

**Comment by fesily** [comment]
#175
