### ISSUE TITLE
lua51 crash 

### ISSUE THREAD

**Issue by fesily** [actboy168/lua-debug#158]
我测试luajit的分支的时候发现一个神奇的bug ,在lua51下可以复现
![image](https://user-images.githubusercontent.com/15152525/154788380-2fcad812-b2a3-47eb-b51a-b7a471c2c4a8.png)
但是把语句改为以下就OK了,我没查出来是哪里的导致的crash
![image](https://user-images.githubusercontent.com/15152525/154788390-cb7b50ed-e41e-4e1f-81c1-157da1c438c4.png)

而且肯定是加载调试的问题.我去掉第一句话,他就正常了.注意:加载调用器里的lua51跑是没问题的,必须是原生没修改过的

系统:macos 12.2.1 CPU: M1 MAX

**Comment by actboy168** [comment]
你可以提供一个test吗

**Comment by fesily** [comment]
截图就是一个完整的test代码

**Comment by fesily** [comment]
能开个wiki吗,我来写点文档

**Comment by actboy168** [comment]
你可以将代码直接发出来，而不是截图。

**Comment by fesily** [comment]
```lua
require "luadebug" : start "@/Users/apple/func/typescripttolua_test/out/debug.sock"  :setup_patch():event "wait"


function setup_patch()
    local rawcoroutineresume = coroutine.resume
    local function coreturn (...)
        return ...
    end
    local coroutine.resume(co,...)
        return rawcoroutineresume(co,...)
        return coreturn(co,rawcoroutineresume(co,...))
    end
end

setup_patch()

local fn = function ()
    
end
co = thread.create(fn)
coroutine.resume(co)
```
