### ISSUE TITLE
如何断点调试Android中使用的lua接口？

### ISSUE THREAD

**Issue by banggu** [actboy168/lua-debug#159]
我的应用会在Android app运行时使用jni去调用lua接口，这种场景该如何使用这个vscode插件调试呢？
README和example中都没有说明此种场景的用法，望大佬看看，谢谢。

**Comment by actboy168** [comment]
我想这就是你要的例子[standalone](https://github.com/actboy168/lua-debug/tree/master/examples/standalone)
