### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by cognitronz** [actboy168/lua-debug#16]
From the topic discussion, it seems that only windows platform is supported.  Can anyone confirm if it will work with Vscode in Ubuntu?

**Comment by actboy168** [comment]
I'm sorry, the debugger does not support linux. I don't have a linux test environment, and debugger.dll support linux should be simple but debugger-inject support linux I have no way, especially for the planned new features.

My current plan is to support x64, support attach to process, support multiple versions of Lua (eg 5.3 and 5.4).

**Comment by mickeyouyou** [comment]
Expect to provide linux version, I will keep watching.

**Comment by actboy168** [comment]
Already support linux.
