### ISSUE TITLE
why not add lua coroutines watcher

### ISSUE THREAD

**Issue by fesily** [actboy168/lua-debug#163]
基于什么考虑没有添加查看所有lua_state的堆栈的功能?  是有什么不能支持的部分吗?

**Comment by actboy168** [comment]
不明白你说的是什么功能

**Comment by fesily** [comment]
就是显示所有的lua_state堆栈

**Comment by actboy168** [comment]
lua的coroutine可能会有很多，全部显示出来，一是性能上会有问题，二是很难在其中找到你关心的coroutine。 

VSCode有计划改进这部分的UI，但是进度比较缓慢，短时间内很难看到结果。
https://github.com/microsoft/vscode/issues/116109

**Comment by fesily** [comment]
👌🏻,的确很有问题
