### ISSUE TITLE
What configuration do I need to debug with the mpv media player?

### ISSUE THREAD

**Issue by stax76** [actboy168/lua-debug#164]
In launch.json do I need "request": "attach" or "request": "launch" ? Or might both work?

I tried both methods and had some success with both, but not full success.

In both cases, the breakpoints were not hit in the lua script that was loaded by mpv, but they were hit in another file called with dofile.

```LUA
local aaa = 'D:\\Work'

package.path = package.path .. ';' .. aaa .. '/?.lua;' .. aaa .. '/?/init.lua'

print "aaa"   -- this showed in an external terminal where I started mpv
require "debugger":start "127.0.0.1:4278":event "wait"
print "bbb"   -- this showed in the VS Code Debug console
dofile('D:/Work/test.lua')   -- in this file it breaks
```

Is maybe the way how mpv loads the script the problem? Code is here:

https://github.com/mpv-player/mpv/blob/master/player/lua.c#L247

I've made a mpv debug build with msys2 and this guide:

https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2

The project I work on is a mpv frontend:

https://github.com/stax76/mpv.net

Perhaps @avih, who is a mpv dev that is active with scripting, can help us. He has helped me before with scripting.

My launch.json config:

```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "address": "127.0.0.1:4278",
        },
        {
            "type": "lua",
            "request": "launch",
            "name": "launch",
            "runtimeExecutable": "D:/Software/Development/MSYS2/mingw64/bin/mpv.exe",
            "runtimeArgs": ["--script=d:\\Work\\delete-current-file.lua", "D:\\Samples\\castele.m2v"],
            "stopOnEntry": false,
            "luaVersion": "5.1",
        }
    ]
}
```

**Comment by stax76** [comment]
> Is the problem about being able to debug lua scripts while running in mpv?

That's it, yes. I learn Lua currently.

**Comment by stax76** [comment]
Here is a mpv debug build:

https://www.mediafire.com/file/2cez89ij61twdaa/mpv-debug.zip/file

**Comment by actboy168** [comment]
This launch.json is enough to load the debugger. 
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "launch",
            "runtimeExecutable": "${workspaceFolder}/mpv.exe",
            "stopOnEntry": true,
            "luaVersion": "5.1",
        }
    ]
}
```

As @sumneko said, mpv doesn't set the chunkname correctly, so the debugger can't get information about the source file.

**Comment by actboy168** [comment]
For mpv's built-in lua, you can use `sourcemaps` to map them to the correct files. But you have to make sure that the mapped file is exactly the same as the file used by mpv. Of course the best solution is to let mpv use the correct chunkname. 
```json

            "sourceMaps": [
                [
                    "mp.*",
                    "${workspaceFolder}/mpv/player/lua/*.lua"
                ],
                [
                    "@*",
                    "${workspaceFolder}/mpv/player/lua/*"
                ]
            ]
```

For non-built-in lua, mpv does not add @ in chunkname, so sourcemap can't solve it either.

**Comment by stax76** [comment]
I have it fully working now, wrote about it in the mpv thread, thank you for your great work and support, greatly appreciated.

**Comment by stax76** [comment]
@actboy168 Change was added to mpv master here:

https://github.com/mpv-player/mpv/commit/84821dbcb6d9e16b8f11da2135208e4f3e66fcd0
