### ISSUE TITLE
如何调试内置的虚拟机呢

### ISSUE THREAD

**Issue by fesily** [actboy168/lua-debug#167]
我有两个思路:
1. `套娃`加载一个lua5.4的remotedebug
2. 加载一个纯lua的调试器
不知道你怎么做的,日志调试吗?
内置的虚拟机没有导出任何的lua接口,都不太能做到

**Comment by actboy168** [comment]
日志调试。

调试器调试调试器的问题是，当你遇到一个bug时，你怎么确定它是哪个调试器引起的。所以你可能需要一个绝对保证无bug的调试器来调试你觉得有问题的调试器。

综上所述，方案一我觉得完全不靠谱。方案二，如果是一个足够简单的纯lua调试器，或许有一定的实用价值。但是我觉得日志是最简单可靠的调试器。

**Comment by fesily** [comment]
ok
