### ISSUE TITLE
Updated visual studio code ver 1.67.0, running debugger errors out with "\" on linux

### ISSUE THREAD

**Issue by Dragon20C** [actboy168/lua-debug#171]
System info: 
Linux Manjaro
Visual Studio Code 1.67.0 (flatpak, also tried normal bin and happens aswell)

This is the error I receive when I now try to run the lua debugger.

```
cd "/home/NAME/Documents/Card Game" ; /home/NAME/.var/app/com.visualstudio.code/data/vscode/extensions/actboy168.lua-debug-1.55.1-linux-x64/runtime/linux-x64/lua54/lua -e "dofile\[\[/home/NAME/.var/app/com.visualstudio.code/data/vscode/extensions/actboy168.lua-debug-1.55.1-linux-x64/script/launch.lua\]\];DBG{582}" "/home/NAME/Documents/Card Game/main.lua" 
/home/NAME/.var/app/com.visualstudio.code/data/vscode/extensions/actboy168.lua-debug-1.55.1-linux-x64/runtime/linux-x64/lua54/lua: (command line):1: syntax error near '\' 
```

**Comment by actboy168** [comment]
This is a bug in VSCode.

**Comment by actboy168** [comment]
Similar to https://github.com/microsoft/vscode/issues/148887

**Comment by Dragon20C** [comment]
thank you for updating me, thanks for the fantastic debugger!
Is there a current work-around, or is my only option is to wait?

**Comment by Dragon20C** [comment]
sorry to bother you again, I am not an expert on visual studio code, could you guide me on the next steps, so what I have done is gone to the debug section and made it create a launch.json file (Heres how it looks like https://pasteall.org/xuSG) I added the "console" : "internalconsole" like you suggested and I tried running debug and just pressing the normal run button I still dont have any output.

**Comment by actboy168** [comment]
using `outputCapture`
