### ISSUE TITLE
Deubgging broken for a vscode extension

### ISSUE THREAD

**Issue by hahn-kev** [actboy168/lua-debug#173]
I'm trying to debug a vscode extension that's running lua (it's a bit complicated), it's this extension https://github.com/sumneko/vscode-lua
from what I can tell when the language server starts up it looks for and loads `\.vscode\extensions\actboy168.lua-debug-1.56.0-win32-ia32\script\debugger.lua` so that the language server can be debugged. However that files gives an error [here](https://github.com/actboy168/lua-debug/blob/8286bc74e48966905ebae02b0409d417b43ba9d6/extension/script/debugger.lua#L114) saying: `The specified module could not be found.` in this case the module is: `/.vscode/extensions/actboy168.lua-debug-1.56.0-win32-ia32/runtime/win32-x64/lua54/remotedebug.dll`

from what I can tell this file was not included in version 1.56.0 of the extension.

As a work around I've downgraded to the 1.55.1 version and manually deleted the 1.56 version of the extension from my vscode extensions folder (required because the debug script picks up the most recent version of the extension regardless of the version in use by vscode), this has fixed the issue.

Edit: this is on windows 11 64bit

**Comment by actboy168** [comment]
It should have recovered by now.

**Comment by hahn-kev** [comment]
Looks like it's working now, thank you.
