### ISSUE TITLE
捕捉exception error行为跟之前版本不一致

### ISSUE THREAD

**Issue by fesily** [actboy168/lua-debug#177]
```lua
local ok,err = pcall(function()
    local ffi = require "ffff"
 end)
```
打开所有断点设置. 除了Caught Errors By lua和 Caught Errors By Native.
这个时候行为应该是不捕捉,因为这个是被pcall包裹的错误. 但是会被Native Errors捕捉
getExceptionCaught(errcode) 读取的是`lua`,`errcode`是2

```lua
   local ffi = require "ffff"
```
只打开uncaught errors,但是不被捕捉.
getExceptionCaught(errcode) 读取的是`native`,`errcode`是2

**Comment by actboy168** [comment]
不明白你在说什么

**Comment by fesily** [comment]
比如说我只打开uncaught errors,但是没有选择上面的异常类型,那么任何异常都不会被捕获,如果我选了异常类型,则无论我选没选 uncaught errors都会被捕获到,等于说下面的Caught Errors By lua和 Caught Errors By Native. uncaught errors三个选项没有任何用处

**Comment by actboy168** [comment]
`uncaught errors`是指没有被任何错误处理捕获的错误，对于lua而言这种错误的结果是crash。

而你举的例子，用lua.exe测试的结果，错误是被lua.exe的lua_pcall捕获，所以不算是`uncaught errors`。

**Comment by fesily** [comment]
第一个例子,被捕获的异常的Native errors,不是uncaught errors,问题是我没选Caught Errors By lua和 Caught Errors By Native.不应该是被捕获的异常都不会提示才对.

**Comment by fesily** [comment]
👌🏻 这个地方有些迷惑性
