### ISSUE TITLE
"launch" debugging not working in 1.58.x

### ISSUE THREAD

**Issue by bleachkitty** [actboy168/lua-debug#182]
Debugging via "launch" no longer works in 1.58.x.  It works normally in 1.57.0.

On 1.58.0, I get an error saying "'inject' is not supported in 'integratedTerminal'".
On 1.58.1, the project launches normally but no breakpoints are hit.
On 1.58.2, the project never launches and there are no errors.

My launch.json is as follows:

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "SpaceSim x64 Debug",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": false,
            "runtimeExecutable": "${workspaceFolder}/../../x64/SpaceSimSFML_D64.exe",
            "cwd": "${workspaceFolder}/../../x64/",
            "luaVersion": "5.3",
        },
        {
            "name": "SpaceSim x86 Debug",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": false,
            "runtimeExecutable": "${workspaceFolder}/../../x86/SpaceSimSFML_D32.exe",
            "cwd": "${workspaceFolder}/../../x86/",
            "luaVersion": "5.3",
        },
        {
            "name": "SpaceSim x64 Test",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": false,
            "runtimeExecutable": "${workspaceFolder}/../../x64/SpaceSimSFML_T64.exe",
            "cwd": "${workspaceFolder}/../../x64/",
            "luaVersion": "5.3",
        },
    ]
}`

I am attempting to launch the first config (SpaceSim x64 Debug).

Please let me know if you need anymore information.

**Comment by actboy168** [comment]
duplicate  #180

**Comment by bleachkitty** [comment]
Yep, the fix in issue #180 fixed it for me.  Sorry about that!
