### ISSUE TITLE
Intellisense in Debug Console

### ISSUE THREAD

**Issue by Sedas25** [actboy168/lua-debug#183]
Hi actboy168,
Is it possible to get Intellisense active in the Debug Console?
My language server is the one from Sumneko.

See the Orange Arrow

Greets Sedas

![image](https://user-images.githubusercontent.com/35778952/173750132-08363af4-c53e-4f7a-a27c-689f5c7a16f8.png)

**Comment by actboy168** [comment]
For now this is difficult. This requires DA and language server to work together. DAP and LSP are two separate protocols. Specific to VSCode, it also doesn't have any protocol associated with it. So it is difficult for a DA to use the functions of another language server.
In most mainstream languages (such as js, python, golang, etc.) in VSCode, DA and language server are actually included in the same extension, so they can solve this problem through private protocols. This also led to the lack of motivation for the VSCode team to actually solve this problem.
Unfortunately lua-debug is just a DA, it doesn't include a language server.

**Comment by Sedas25** [comment]
Ok thank you :)
Then I'll see if I can program something ^^
