### ISSUE TITLE
vscode这边日志在哪里

### ISSUE THREAD

**Issue by exploman** [actboy168/lua-debug#188]
有时attach下启动调试后闪退，希望能看到客户端这边的日志。目前是使用商店下载的二进制版本

**Comment by exploman** [comment]
~/.vscode-server/extensions/actboy168.lua-debug-1.58.2-linux-x64 有一个client.log，不过其中报的错误是调试其他程序的时候输出的。现在我想调试freeswitch中的lua脚本，vscode连上后，一到二秒后就会断开，也看不到断点命中，也在client.log中也看不到日志输出。

**Comment by exploman** [comment]
使用了，ssh remote

**Comment by actboy168** [comment]
日志就在根目录下。不过大多数情况下不会有日志输出，需要日志要自己加。
