### ISSUE TITLE
Luarocks support?

### ISSUE THREAD

**Issue by Frityet** [actboy168/lua-debug#192]
How could I make the plugin work with a project I created with `luarocks init`?

Here is my `launch.json`

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/tests/main.lua",
            "luaexe": "${workspaceFolder}/lua",
            "luaVersion": "jit",
        }
    ]
}
```

**Comment by actboy168** [comment]
I don't know about luarocks. 

Maybe you can remove `"luaexe": "${workspaceFolder}/lua"`.

**Comment by Frityet** [comment]
[Luarocks](https://luarocks.org/) has a shell script in `${workspaceFolder}/lua`

**Comment by Nilegfx** [comment]
I am also interested to achieve the same as @Frityet . any idea how  can we incorporate  luarocks with this nice debugging extension?

**Comment by Frityet** [comment]
> I am also interested to achieve the same as @Frityet . any idea how  can we incorporate  luarocks with this nice debugging extension? 

Alright so with enough elbow grease I was able to get it to work, basically you need to run luarocks make before trying to execute the file which should be in the lua_modules dir (look in the subdirs). Make sure you setup the launch settings to make the LuaRocks loader run on launch. You will have to adjust path and c path to make it work. I will write a proper tutorial later!

**Comment by Frityet** [comment]
@Nilegfx https://github.com/actboy168/lua-debug/issues/202
