### ISSUE TITLE
Lua Debug: Launch Process not working since version 1.60.0

### ISSUE THREAD

**Issue by benjaminGoldenRace** [actboy168/lua-debug#198]
In the last version 1.60.0 I can't debug lua code with my embedded lua application, version 1.59.0 works properly.
The application is launched, but the debugger doesn't attach to the launched application.
I've tested with lua version 5.3 and also updated to the last lua version 5.4.4 and with both versions the same thing happen.
Testesd on Windows.

**Comment by actboy168** [comment]
Can you provide an example?

**Comment by benjaminGoldenRace** [comment]
I'm sending you a simple test with my embeded lua executable. I've just seen this message in the console with the version 1.60.0.

`(debugger.lua):129: %1 is not a valid Win32 application.`

With the plugin version 1.59.0 works properly. My executable is a 32 bit application, maybe this is related with that?

[TauScript.zip](https://github.com/actboy168/lua-debug/files/9743726/TauScript.zip)

**Comment by jjonethal** [comment]
@actboy168 d6914b7 saved my life :-) just hand patched my 1.60
