### ISSUE TITLE
love2D support 

### ISSUE THREAD

**Issue by dpMerchant** [actboy168/lua-debug#20]
Hello,

Is there a way to add love2D code support?

**Comment by mika76** [comment]
Is there any way to enable support for lua 5.1 (I'm asking for corona sdk) - maybe by disabling some functionality only supported in 5.3+

From google translate:
有没有什么办法来启用对lua 5.1的支持（我要求corona sdk） - 也许通过禁用一些仅支持5.3+

**Comment by actboy168** [comment]
Lua’s ecosystem is very confusing. Just supporting one version has been very troublesome. So I don't have time to support more versions.
Maybe you can choose another debugger, such as a debugger written in pure lua. These debuggers are more portable and have better compatibility, but I don't like them.

**Comment by mika76** [comment]
> but I don't like them.

Ha ha neither do I 😄 

I was really looking for a vscode debugger, and it's sad that Corona and Love only use old Lua versions ☹️ Unfortunately creating another full lua debugger for vscode is a little out of my range at the moment.

**Comment by nikeinikei** [comment]
you can compile love yourself with lua 5.3 / 5.4 as the backend. Although then you're missing out on a lot of performance.

**Comment by jinwenhua** [comment]
a lot of lua lib only support lua5.1, I really want a lua5.1 runtime too

**Comment by actboy168** [comment]
Already supported.
