### ISSUE TITLE
Debugging mpv media player on Linux

### ISSUE THREAD

**Issue by stax76** [actboy168/lua-debug#207]
On Windows, I successfully used lua-debug, now I want to try using lua-debug on Linux. For this, I compiled mpv with debug symbols. When I start debugging, I get the message `'runtimeExecutable' need specify inject or address`, my launch.json config is:

```JSON
{
    "name": "mpv lua linux",
    "type": "lua",
    "request": "launch",
    "console": "internalConsole",
    "runtimeExecutable": "mpvd",
    "runtimeArgs": ["--script=${file}", "/media/user/Data/Samples/demo.mkv"],
    "stopOnEntry": false,
    "luaVersion": "5.1"
},
```

Is there something wrong with my configuration, or maybe with my mpv build?

**Comment by actboy168** [comment]
Process injection is only implemented on windows. You need to inject the debugger yourself, and let vscode connect to the debugger. e.g.
https://github.com/actboy168/lua-debug/tree/master/examples/attach

```json
{
    "name": "mpv lua linux",
    "type": "lua",
    "request": "launch",
    "console": "internalConsole",
    "runtimeExecutable": "mpvd",
    "runtimeArgs": ["--script=${file}", "/media/user/Data/Samples/demo.mkv"],
    "address": "127.0.0.1:12306",
    "stopOnEntry": false,
    "luaVersion": "5.1"
},
```

**Comment by stax76** [comment]
I see, thanks.
