### ISSUE TITLE
I'm trying to write a plugin for a game that uses Lua.

### ISSUE THREAD

**Issue by maskelihileci** [actboy168/lua-debug#210]
There is a game that uses Lua 5.3. The game has functions that are distributed to modders for use. I want to use VSCODE to call and debug these functions within the game, but I have not been able to do so with this extension. Is there a way to do this?

**Comment by actboy168** [comment]
If the program has exported lua symbols, then you can manually load the debugger, for example
https://github.com/actboy168/lua-debug/tree/master/examples/attach

If it's not exported, you won't be able to debug it.

**Comment by maskelihileci** [comment]
Thank you for your help.
