### ISSUE TITLE
Module X not found

### ISSUE THREAD

**Issue by 5angar1us** [actboy168/lua-debug#211]
Hello, I am getting the error "module X not found".

Structure of my project
- progect_folder
  - .vccode 
  - src
    - lualib.lua
    - main.lua

lualib.lua
```
function getName()
    return "George"
end
```

main.lua
```
local lualib = require("lualib")
print("Hello, world and "..getName())
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "Debug",
            "cwd" : "${workspaceFolder}/src",
            "stopOnEntry": false,
            "program": "${workspaceFolder}/src/main.lua",
        }
    ]
}
```

**Comment by 5angar1us** [comment]
I found a solution in https://github.com/actboy168/lua-debug/issues/203

I changed the launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "Debug",
            "path": "${workspaceFolder}/src/?.lua",
            "stopOnEntry": false,
            "program": "${workspaceFolder}/src/main.lua",
        }
    ]
}
```
It works for me, but I don't understand why because I configured under the documentation https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes

**Comment by actboy168** [comment]
It looks like you have found your answer, I don't understand what is your problem now?

**Comment by 5angar1us** [comment]
In my opinion because of this https://www.lua.org/pil/8.1.html
