### ISSUE TITLE
怎么使用远程调试呢，是否有相关文档可以查看？

### ISSUE THREAD

**Issue by tincopper** [actboy168/lua-debug#219]
想要使用远程调试Openresty的lua代码，请问一下这个可以支持吗？目前没有发现该怎么样使用远程调试

**Comment by actboy168** [comment]
https://github.com/actboy168/lua-debug/tree/master/examples/standalone

**Comment by tincopper** [comment]
> https://github.com/actboy168/lua-debug/tree/master/examples/standalone

好的，谢谢了，试了一下可以实现在openresty远程调试了。
1、需要引入debugger.lua文件到项目之后，同时需要将 debugger.lua文件的中path换成插件的安装目录
2、然后在需要打断点的代码位置引入`require("lualib.debugger"):start "0.0.0.0:12306":event "wait"`即可

但是发现另外一个问题就是在发送了一次请求之后再如果再发请求进程就会被卡住，也没有断点提示。需要重启openresty才可以继续。

**Comment by actboy168** [comment]
我重现不了

**Comment by fesily** [comment]
> > https://github.com/actboy168/lua-debug/tree/master/examples/standalone
> 
> 好的，谢谢了，试了一下可以实现在openresty远程调试了。 1、需要引入debugger.lua文件到项目之后，同时需要将 debugger.lua文件的中path换成插件的安装目录 2、然后在需要打断点的代码位置引入`require("lualib.debugger"):start "0.0.0.0:12306":event "wait"`即可
> 
> 但是发现另外一个问题就是在发送了一次请求之后再如果再发请求进程就会被卡住，也没有断点提示。需要重启openresty才可以继续。
先确认一下lua_hook事件有没有继续执行
当前架构不允许除了调试器不能使用lua_hook
