### ISSUE TITLE
Failure to detect source files from chunks

### ISSUE THREAD

**Issue by Silverlan** [actboy168/lua-debug#235]
Hello!

Thank you for this extension! This will be very useful for me if I can get it working properly.
I've got the remote connection to my program working, but I'm having some issues with breakpoints.

My Lua test-file is located in "pragma/lua/test_luadebug.lua". It has the following content:
```lua
for i=1,100000 do
    print("Test" .. i)
end
```
It is loaded using `luaL_loadbuffer` and the chunk name for it is "lua/test_luadebug.lua".

Here is my `launch.json` configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "pragma",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "address": "127.0.0.1:12306",
            "sourceMaps": [
                [
                    "lua/test_luadebug.lua",
                    "${workspaceFolder}/lua/test_luadebug.lua"
                ]
            ]
        }
    ]
}
```

The workspace folder is `pragma`. I have also tried specifying the absolute path like so:
```json
            "sourceMaps": [
                [
                    "lua/test_luadebug.lua",
                    "F:/projects/pragma/lua/test_luadebug.lua"
                ]
            ]
```

The "Loaded Scripts" section in Visual Studio Code is completely empty. When I run `test_luadebug.lua` and then break manually while it's still running, a `<Memory>` file opens with this line:
```
lua/test_luadebug.lua
```
(I assume that's the chunk name of the currently running file.)

The breakpoints in the file still say "Wait verify. (The source file is not loaded.)". What else could I try?

Thank you!

**Comment by actboy168** [comment]
The correct chunkname should be `@lua/test_luadebug.lua`.

**Comment by Silverlan** [comment]
> The correct chunkname should be `@lua/test_luadebug.lua`.

Thanks for the quick response! I've tried your suggestion, but unfortunately the problem still persists:

```json
            "sourceMaps": [
                [
                    "@lua/test_luadebug.lua",
                    "${workspaceFolder}/lua/test_luadebug.lua"
                ]
            ]
```

This does not work either:
```json
            "sourceMaps": [
                [
                    "@lua/test_luadebug.lua",
                    "F:/projects/pragma/lua/test_luadebug.lua"
                ]
            ]
```

**Comment by actboy168** [comment]
sourceMaps does not need to be changed.

**Comment by Silverlan** [comment]
> sourceMaps does not need to be changed.

Alright, changing the actual chunk name seems to have made a difference, however breakpoints are still not functional.

The file is now listed in the "Loaded Scripts" section and when I run the script and break **manually**, it correctly breaks in the line that is currently being executed:
![Code_2023-03-17_17-18-51](https://user-images.githubusercontent.com/3609960/225961193-73ce4f23-587f-49a4-bd7d-9b97d3e8070a.png)

However, if I set the breakpoint, it still says the file is not loaded and it does not get triggered when I execute the file:
![Code_2023-03-17_17-20-32](https://user-images.githubusercontent.com/3609960/225961337-f9e124ef-b08c-45b7-a783-f1fc3935d13a.png)

So breaking manually works, but breakpoints do not.

**Comment by actboy168** [comment]
Are you using 1.61.0?

**Comment by Silverlan** [comment]
I'm not sure how to tell, I did not see any version tags anywhere. I'm on commit 6837200 ( https://github.com/actboy168/lua-debug/commit/68372005f95173cf2d6a3379d40a068f50b3f0dd ).

**Comment by Silverlan** [comment]
Here's a video of the problem:
https://user-images.githubusercontent.com/3609960/226103077-287d0fe1-642a-4bc1-ac55-ca746d45babd.mp4

Maybe I'm just missing something obvious?
I tried reverting to commit 567fe0c (v1.61.0), but the build instructions appear to be different for that version and I wasn't able to get it running. For the video I tried the latest commit (4658406).

**Comment by actboy168** [comment]
I've fixed it in the latest commit. However, the master is still unstable.

**Comment by Silverlan** [comment]
Can confirm that it's now functional, thanks again!
