### ISSUE TITLE
Selecting lua version to compile against for rdebug

### ISSUE THREAD

**Issue by thewhitegoatcb** [actboy168/lua-debug#254]
Hello,
Im trying to run the debugger on a game called Vermintide 2 it runs an older version of the original luajit 2.1 b3, also has some sandboxing measures for dofile,load,require,io,loadlib.
I have managed to write my own loader to restore the original environment and the game works perfectly, however when im trying to either load the debugger with the pre compiled bins, it crashes when I attach VSCode (using the https://github.com/actboy168/lua-debug/tree/master/examples/attach as a base) the crash is inside of remotedebug.dll itself, couldn't pin point the exact issue.
I recompiled luadebug as in README, now it crashes just as the rdebug tried to load in 
https://github.com/actboy168/lua-debug/blob/237e5594c652b7af2f0affeb460a47d2ce8a4fe3/src/luadebug/rdebug_hookmgr.cpp#LL509C7-L509C7

Is it possible to select the lua version to compile with? it seems to always copy the lua54 headers from bee

**Comment by actboy168** [comment]
This is just the lua used internally by luadebug, and has nothing to do with the debug target.

If you compile luadebug correctly using luajit source files, it should not crash here, because only non-luajit will run here.

**Comment by thewhitegoatcb** [comment]
Thank you for the quick reply,
It was an issue with lua version detection as tostring was replaced with their own version and this check failed
`if (tostring(assert):match('builtin') ~= nil) then`
I have restored the original, but now I have a different crash
![image](https://user-images.githubusercontent.com/69012729/235842587-bec8cafe-f36e-4fc6-a5b4-217738b130f3.png)

**Comment by actboy168** [comment]
LUA_HOOKTHREAD is a patch to provide more debugging information to luadebug, it is optional.

**Comment by thewhitegoatcb** [comment]
Compiles fine now, Thank you.
still crashes for some reason, I think im not using the correct luajit build they used in the game, btw how can I enable debug symbols for release builds? not sure if debug builds produce compatible luajit version

**Comment by actboy168** [comment]
If you are using luamake, just need `luamake -mode debug`

**Comment by thewhitegoatcb** [comment]
Thanks for the help, I will close the issue for now as I didn't have time to sort the luajit issues that are unrelated to your plugin.
If I have another issue with the correct luajit version I will open a new issue, much appreciated
