### ISSUE TITLE
Performance while debugging

### ISSUE THREAD

**Issue by thewhitegoatcb** [actboy168/lua-debug#259]
Hello,
I have compiled lua-debug with luajit(nogc64) of this commit: https://github.com/LuaJIT/LuaJIT/tree/a44f53acf53603e7d9b88352de035b1804be4e88
as the later commit has breaking features of the game im trying to debug(table ordering issues).
The debugger works fine, everything is stable but the performance is about x50+ times slower than running without a debugger.
Is it normal or im missing out on some massive performance on not using the later luajit builds or using your modified luajit fork ?
P.S. I cannot easly test commits that are past the one that I linked

**Comment by thewhitegoatcb** [comment]
Update:
Managed to update to the current modded luajit fork from this repo.
Performance is still bad, things I observed: 
When attaching with `"stopOnEntry": false,` and no breakpoints set, the performance is good but as soon as I pause execution  and continue or set a breakpoint anywhere,  it slows down badly from capped 60fps to 1~ fps, it recovers if I remove the breakpoint.
Is that normal or is it the expected performance ?

**Comment by actboy168** [comment]
@fesily

**Comment by fesily** [comment]
Does this happen in functions of any size? How can breakpoints in large functions cause a dramatic performance drop?

**Comment by thewhitegoatcb** [comment]
> Does this happen in functions of any size?

just tested anything from 2-50~ lines functions, local funcs, table member funcs, all seem to cause slow downs

**Comment by thewhitegoatcb** [comment]
No idea if it could hint at what's happening but all C functions with `function_name` seem to give off a wrong name 
![image](https://github.com/actboy168/lua-debug/assets/69012729/9f3082e4-7e4d-435d-bf69-3adefe218fa5)
Address provided by `tostring` is correct

**Comment by fesily** [comment]
LUAJIT_DISABLE_GC64 I have not tested it, I'm not sure if it's because this flag is enabled.

**Comment by fesily** [comment]
You can provide a minimal test case, let me try

**Comment by fesily** [comment]
Or you can provide a flame chart, and let's check which code is running slow

**Comment by thewhitegoatcb** [comment]
> 

I will try to produce one in the next few hours, unsure if just a small test case would be representable but I didn't try

**Comment by thewhitegoatcb** [comment]
![image](https://github.com/actboy168/lua-debug/assets/69012729/dc5e80a3-7880-4b17-9113-405bb41d54da)
Captured 16 secs with xperf, 15.6s out of 16s of the main thread is occupied by `hookmgr::full_hook_callback`
This is with one breakpoint active.

**Comment by thewhitegoatcb** [comment]
Had another go,
![image](https://github.com/actboy168/lua-debug/assets/69012729/036ac9cf-8155-4dc1-8b0e-c74b6184c846)
This is gsub being called a lot of times from `normalize_win32` in `backend\worker\filesystem.lua`.

I think I should clarify of the Lua environment of the game:
The game has compressed file packages with compiled luajit scripts, they are being uncompressed and loaded by the game via `luaL_loadbuffer`.
The files contain debug info with the relative script file path like `scripts/unit_extensions/health/lure_health_extension.lua`, to be clear the file doesn't actually exist on disk.

The game replaces `require,dofile,loadfile` with their own version to look for the scripts in the compressed packages.
Currently I override _some_ scripts that are being executed from these packages with files on disk by calling the original `require,dofile,loadfile`, There I place the breakpoints and able to debug fine (except the performance)

**Comment by fesily** [comment]
Try use the flag: pathFormat=linuxpath or sourceFormat=linuxpath

**Comment by thewhitegoatcb** [comment]
> Try use the flag: pathFormat=linuxpath or sourceFormat=linuxpath

Tested any combinations of those, fully restarting the game for each test.
Setting any of those causes BP not to trigger at all, and still lags.
if I only set `pathFormat=linuxpath` and try to remove the BP ,the performance doesn't recover and still lags til I disconnect the debugger.

**Comment by fesily** [comment]
Fine, I will try to fix

**Comment by thewhitegoatcb** [comment]
> Fine, I will try to fix

Thanks, let me know if I need to do test, or more profiling.
Is there a way for me to debug `lua-debug` itself ?

**Comment by fesily** [comment]
only print when debug lua-debug. I downloaded the game, how do I start the debugger in the game?

**Comment by thewhitegoatcb** [comment]
> only print when debug lua-debug. I downloaded the game, how do I start the debugger in the game?

The game doesn't have it's own debugger, im using my own project to start and load the debugger,
do you have discord ?  you can add me at  WhiteGoat#6317
