### ISSUE TITLE
插件冲突问题

### ISSUE THREAD

**Issue by tiansin** [actboy168/lua-debug#26]
我用的是最新版本的VsCode,使用的是默认的调试配置,F5启动调试后只会停在入口,无法单步调试,停止也要按两次才行.
经过我不断的禁用启用我安装的扩展测试,最终锁定问题是这个插件与LiveShare插件有冲突,具体原因不明
https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare

**Comment by actboy168** [comment]
这个你去找微软更好。虽然我觉得他们并不打算维护这个用来吹牛的插件。
