### ISSUE TITLE
程序一启动就终止运行了

### ISSUE THREAD

**Issue by littleShy** [actboy168/lua-debug#27]
我们公司使用的是内嵌lua运行的, 在配置完lanch.json后, 启动起来程序,立马就停止运行了,不止为何
"type":"lua",
"request":"launch"
"name":"Launch",
"runtimeExecutable"":"exe path",
"cwd":"script path",
"stopOnEntry":true,
"sourceMaps" [ [目录映射] ]

**Comment by liudibo** [comment]
我也遇到了这个问题，调试c代码发现是lua_open()直接就挂了，是不是跟64位有关？如果是，如何在配置中设置64位相关信息呢？谢谢

**Comment by actboy168** [comment]
@liudibo 如何配置64位，看readme

**Comment by liudibo** [comment]
@actboy168 readme认真的看了，但是没有领会其中奥义。我给你的gmail发了邮件，麻烦抽空帮忙看下，万分感谢

**Comment by actboy168** [comment]
@liudibo 
1. readme已经包含所有我想说的内容，如果你不明白，你要指出你不明白的点，这样我才能给你解答
2. 提问题不要用gmail，就用iusses就好
3. 这个iusses我关了，你有问题自己开新的iusse
