### ISSUE TITLE
Detach the debugger

### ISSUE THREAD

**Issue by Sedas25** [actboy168/lua-debug#279]
Is it possible to detach the debugger from a running lua state without killing the Process ?

Reason: we have an application with a realy expensive build up, so it's need 4+ seconds before I can execute a lua code.
I have the plan to start the Application and execute the debugger in vscode with the second applications that send over a Named pipe the lua file. So the main application is not required too build up every debug session.

**Comment by actboy168** [comment]
Use attach mode.

**Comment by Sedas25** [comment]
but in the attach mode i cant press F5 again to launch another script

i want:
F5 -> start the script & debug -> run ...... -> script end debugger disattach -> vscode end debug mode.

but the Main Application is still running.

Now in the attach mode the debug in vscode is still active

**Comment by actboy168** [comment]
Do you want the running process to execute a Lua script? This is not the debugger's job.

**Comment by Sedas25** [comment]
No, I want the debugger to detach/send to VS code that the debug job is done after the lua script is over.
But the main application remains on.
Currently VSCode finishes the debug job only when the main application is finished.

**Comment by actboy168** [comment]
So this is the attach mode.
