### ISSUE TITLE
无法Attach的问题

### ISSUE THREAD

**Issue by Clevergua** [actboy168/lua-debug#282]
您好,想问一下是不是Debugger attach只支持dll,dylib的lua调用.而.lib .a不可以呢?

**Comment by actboy168** [comment]
.a只是一个编译阶段的中间结果，无法运行。

首先要可以运行，再来讨论可不可以attach的问题。

**Comment by Clevergua** [comment]
> .a只是一个编译阶段的中间结果，无法运行。
> 
> 首先要可以运行，再来讨论可不可以attach的问题。

是一个使用lua的.lib, mac上用的.a静态库的C语言的项目,目前是可以运行的,但是attach到process后没办法进入lua脚本的断点,想请教一下还需要做哪些工作才能成功断点到...

**Comment by Clevergua** [comment]
<img width="797" alt="Screenshot 2023-12-21 204201" src="https://github.com/actboy168/lua-debug/assets/53552547/a22d510e-2b6d-45f1-9a3a-b13f9b6db5ff">

看样子debugger的dll都加载进来了

**Comment by Clevergua** [comment]
测试结果: 采用动态库编译的Lua库的调用可以Debugger而静态库不能.
