### ISSUE TITLE
VS Code lua-debug plugin:  "Install in WSL: Ubuntu" does not work!

### ISSUE THREAD

**Issue by bojh** [actboy168/lua-debug#284]
tried to install the lua-debug plugin in a WSL-Ubuntu connected VS-Code instance does fail and creates following error message:
**Can't install 'actboy168.lua-debug' extension because it is not compatible with the current version of Visual Studio Code (version 1.84.2).**
I haven't found any solutions for that issue. 
Is there any idea? ... or still not yet possible?

**Comment by actboy168** [comment]
I can't reproduce.

**Comment by bojh** [comment]
Hello @actboy168,
I have updated my VS Code to 1.85.0 - and the problem has gone. 
I do not know if it was the root cause - today it work's -thanks for your immediate response.
will close the issue.
