### ISSUE TITLE
Does debugger not work when LUA_IDSIZE is greater than 64?

### ISSUE THREAD

**Issue by YuhiFanta** [actboy168/lua-debug#286]
I'd like to use this to debug a custom lua environment(xlua, LUA_IDSIZE is set to 120). When I attached, debugger and host application both crashed, but debugging works when I set LUA_IDSIZE less than or equal to 64.
调试器无法在LUA_IDSIZE大于64的lua环境中工作？我想调试一个自定义的lua环境（xlua，LUA_IDSIZE 设置为120），附加以后调试器和宿主程序都崩溃了，但是设置为64或者以下就可以工作。

**Comment by actboy168** [comment]
如果你修改过lua的代码，你需要用你修改过的lua编译一个调试器。

**Comment by YuhiFanta** [comment]
明白了，谢谢
