### ISSUE TITLE
为什么在调试控制台内输入会出现 `evaluate` not yet implemented.(idle)

### ISSUE THREAD

**Issue by yuchaoo** [actboy168/lua-debug#30]

**Comment by yuchaoo** [comment]
本来我想实现的是在控制台输入GM命令，然后交给程序去处理，这种情况下我该怎么做？还有就是在lanunch process模式下"console":"externalTerminal", 这个配置貌似不生效

**Comment by actboy168** [comment]
不暂停，没有通用的方法可以执行lua。你可以自己实现这个功能
