### ISSUE TITLE
C++ attach 调试

### ISSUE THREAD

**Issue by qiuzijian7** [actboy168/lua-debug#39]
我在C++中创建debugger，等待vscode链接，但是始终链接不上，请问我是哪里写错了么
```
	debugger_create("127.0.0.1:4278");
	debugger = debugger_get();
	debugger->wait_client();
	debugger->attach_lua(State);
```

**Comment by qiuzijian7** [comment]
vscode中，launch.json配置如下：
`{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "ip": "0.0.0.0",
            "port": 4278
        }
    ]
}`

**Comment by actboy168** [comment]
连接本地请用127.0.0.1

**Comment by qiuzijian7** [comment]
vscode使用的是x86版本的dll，我本地使用的是自己用源码编译出来的x64版本的dll，会是这个问题么

**Comment by actboy168** [comment]
应该已经可以了

**Comment by actboy168** [comment]
attach我测试是没问题的，也许你应该试下你的客户端和服务端之间是否能连通
