### ISSUE TITLE
debugger编译成Android和iOS版本

### ISSUE THREAD

**Issue by mybios** [actboy168/lua-debug#40]
我们在使用Unity+lua开发一款大型手机游戏。
现阶段我们项目使用远程调试的方式通过vscode调试unity游戏。
debugger被编译成windows的dll可以正常的运作，但iOS版和Android版无法编译出来，我们希望可以通过远程调试的方式调试手机上的脚本，不知道能否支持？

**Comment by actboy168** [comment]
我在维护的另一个闭源版本支持移动平台，我正在试图缩小这个两个版本之间的差距，但需要一段时间。在此之前，欢迎任何与此相关的pull request。

**Comment by mybios** [comment]
好的，谢谢。

**Comment by actboy168** [comment]
现在调试器已经支持iOS。虽然我没有测试Android，但我认为移植的难度已经不大，也欢迎与此有关的pull request。
