### ISSUE TITLE
 Lua 目录操作lua对目录的操作主要依赖lfs库,所以头文件必须要require 'lfs'

### ISSUE THREAD

**Issue by feishen54** [actboy168/lua-debug#43]
这标题，是截取百度找到的一句话。
是这样的，我需要读取一个文件夹内的所有文件，所以想用方便的方式去读取，而不是手填文件路径，但是我试过能百度到的函数，都没有一个能直接读取的，比如标题那个，就会提示没有这个库 'lfs'
而我只会lua语言，其它都不会了，所以，只能请教别人怎么能做到。
不想学习c或者其它语言，因为只是一个读取功能而已，实在没办法，也可以手填路径，相对而言成本低点。

我想请问，就我这个条件，应该怎么去做，能用较低的成本达到这个目的呢？ 0 0

**Comment by actboy168** [comment]
这个问题和调试器无关。你需要一个filesystem库，例如[bee.lua](https://github.com/actboy168/bee.lua)

**Comment by feishen54** [comment]
> 这个问题和调试器无关。你需要一个文件系统库，例如[bee.lua](https://github.com/actboy168/bee.lua)
能否帮忙给个简单的使用方法，怎么在vscode里使用相关方法，因为看不懂 bee.lua ，  .......
谢谢啊 0 0

**Comment by actboy168** [comment]
找她 @sumneko 手把手教你吧

**Comment by feishen54** [comment]
> 找她@sumneko手把手教你吧
好的  0 0
