### ISSUE TITLE
调试时偶尔会弹出lua窗口

### ISSUE THREAD

**Issue by sumneko** [actboy168/lua-debug#45]
在调试设置中指定了自己的lua.exe:
"luaexe": "${workspaceRoot}\\server\\bin\\lua-language-server.exe",
"luadll": "${workspaceRoot}\\server\\bin\\lua54.dll",

![image](https://user-images.githubusercontent.com/5213431/53395239-4bdeed00-39dc-11e9-952e-0ea484a5e2b0.png)

**Comment by actboy168** [comment]
应该已经没问题了
