### ISSUE TITLE
在Ubuntu19.04下使用时出现convertToDto unexpected type错误

### ISSUE THREAD

**Issue by WinsonSS** [actboy168/lua-debug#49]
你好，我在Ubuntu19.04下使用使用Lua Debug时出现了"convertToDto unexpected type"错误，我安装了vscode下的lua和lua debug插件并且系统安装了lua5.3，请问是要安装其他依赖还是什么问题？

**Comment by actboy168** [comment]
https://github.com/actboy168/lua-debug/blob/master/extension/README.md#build-for-macoslinux

**Comment by WinsonSS** [comment]
> https://github.com/actboy168/lua-debug/blob/master/extension/README.md#build-for-macoslinux

在按照你给的build过程build的时候出错说找不到文件，报错信息如下：
_[0/3] cd 3rd/bee.lua && ninja -f ninja/linux.ninja
ninja: error: loading 'ninja/linux.ninja': No such file or directory
FAILED: build/linux/_/bee 
cd 3rd/bee.lua && ninja -f ninja/linux.ninja
ninja: build stopped: subcommand failed.
_

**Comment by actboy168** [comment]
```bash
git submodule update --init
```
