### ISSUE TITLE
进程管理器中文乱码问题

### ISSUE THREAD

**Issue by rhubard** [actboy168/lua-debug#52]
进程管理器中文乱码问题，导致F5没反应（界面已经是简体中文），请问如何解决

<img width="953" alt="微信图片_20190501115037" src="https://user-images.githubusercontent.com/26682689/57005125-b04e4080-6c07-11e9-8120-35bdaed04eb1.png">

**Comment by actboy168** [comment]
乱码应该是你的进程管理器不支持中文的原因。
不过此前，新的调试后端确实没有实现对中文的支持。我现已经加上，但是我没有中文的windows用户名，所以没有测试过你的情形。但中文名的代码路径已经可以正常工作了。
