### ISSUE TITLE
Crash when require is called

### ISSUE THREAD

**Issue by VenoMpie** [actboy168/lua-debug#54]
Hi

The debugger crashes when requiring a dll

for i, lib in ipairs( _module ) do
        _ = _global[ lib ] or require( lib )

As soon as it hits require( lib ) then the debugger stops

**Comment by actboy168** [comment]
I don't understand your problem. Can you provide the code that caused the crash?

**Comment by VenoMpie** [comment]
Trying to debug this https://github.com/luadch/luadch/releases -> 2.19
I run core/init.lua. It debugs fine until it tries to require the DLL then the session crashes. Unless I'm going it wrong?

**Comment by actboy168** [comment]
Debugger only supports lua5.3 and lua5.4

**Comment by VenoMpie** [comment]
Cool thanks. I did try and hack the debugger to use 5.1 but that didn't work out so well :)
Closing as this is not an issue then.
