### ISSUE TITLE
attach模式是否能提供案例？谢谢大大

### ISSUE THREAD

**Issue by ArkYk** [actboy168/lua-debug#59]

**Comment by actboy168** [comment]
launch实则就是启动进程+attach，所以launch模式就是最好的例子

**Comment by ArkYk** [comment]
谢谢大大，我描述一下我现在的情况。第三方的exe调用了一个.lua，我需要能实时调试这个.lua不知道可不可行？lua是刚开始琢磨，对这一块不是很熟。

**Comment by actboy168** [comment]
一般用launch就行

**Comment by ArkYk** [comment]
> 一般用launch就行

emmm...我这种情况下launch.json配置是按照readme.md中的第二种方式配置吗？
**launch模式，启动一个进程(比如lua.exe或者其他动态链接了luadll的exe)并调试。如果需要调试的目标和lua.exe的行为不一致，可以采用这个模式。**

**Comment by Vecol** [comment]
试了下debug Unity里面的lua代码会直接报下面的错误, 用的是tolua这个插件，应该是魔改过的dll
![图片](https://user-images.githubusercontent.com/13953965/58857085-ebe09c80-86d6-11e9-8591-053065d4a4a9.png)
配置是这样的
```json
        {
            "name": "lua attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "processName": "Unity.exe",
        },
```

**Comment by actboy168** [comment]
错误提示应该已经说得很清楚了
