### ISSUE TITLE
建议默认提供的lua5X.dll一起提供lua5X.lib文件

### ISSUE THREAD

**Issue by RelicOfTesla** [actboy168/lua-debug#61]
使用vscode插件自带的那个lua5X.dll的话，会与个人使用的lua版本出冲突。。。如*multiple Lua VMs detected*
作者君提供的lua53是lua535的。。太新了。所以很悲伤github.com/luaDist/lua是使用532的。冲突。
于是想指向自己的lua.exe，然而没用，F5直接卡住。。
看了下文档，不是有改了lua.dll么，所以使用官方lua.exe/dll编译出来的，调试不了。配置luaexe对我等人来说是没用的。。。
```
            "luaexe": "${workspaceFolder}/../lua.exe",
```
搜了下，插件目录带了lua5x.dll，不如请作者君直接提供.lib文件，这样我就可以直接link到作者君上的dll上调试了。。免去还得手工导符号之心酸。

**Comment by actboy168** [comment]
官方版本的lua可以调试，只是缺少一些功能。调试器自带的版本导出符号和官方版本完全一致，所以提供lib没有意义。
