### ISSUE TITLE
最新版的print(stdout)输出不显示，无法中途断点

### ISSUE THREAD

**Issue by RelicOfTesla** [actboy168/lua-debug#62]
```
local i=0
while true do
i = i + 1
print(i)
end
```

断点调试，单步，可以显示print。放开F5，vscode不显示了print内容了，且无法中途断点。
尝试着调整console或outputCapture，无效。扔到ter

另外，手工执行
```
C:\Users\Administrator\.vscode\extensions\actboy168.lua-debug-1.3.6\runtime\win32\lua53\lua.exe   test.lua
```
可以显示

----

```
win10
lua debug 1.3.6

vscode版本：
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
```

**Comment by RelicOfTesla** [comment]
尝试了下，这个配置是可以的输出和断点的。
···
"console": "integratedTerminal",
            "outputCapture": [
            ],
···

**Comment by actboy168** [comment]
我不明白你为什么要写这种代码，这和死循环没什么区别。默认的终端之所以可以看起来正常工作，是因为它使用来同步的标准输出，所以尽管是死循环1秒也顶多跑几千次。如果不受终端的影响这个速度至少还能快上几千倍。调试器使用的是异步缓冲，一跑起来就把你的资源撑爆了。

**Comment by RelicOfTesla** [comment]
上面只是举例，实际我的LUA工程是在做一些穷举算法。
实践中，死循环业务应该还是蛮多的，例如http爬虫，http/sql服务器监控之类的，都是很正常。（有接入自己的sleep接口）

**Comment by RelicOfTesla** [comment]
另外，无法中途断点也是BUG哦。要是代码不小心写错成死循环，反而无法调试断点排错，误判反而会导致雪上加霜的排错负担。

**Comment by actboy168** [comment]
我想我已经说得很清楚了，调试器也是运行在你电脑上的一段代码，运行代码就需要资源，没有资源任何代码都无法正常运行。

**Comment by RelicOfTesla** [comment]
可以考虑缓冲区到达封顶后，阻塞运行。也就是push limit+wait的设计。go的channel设计也是如此。到达limit值后，阻塞push。
