### ISSUE TITLE
左栏Globals的展开状态

### ISSUE THREAD

**Issue by Fedora7** [actboy168/lua-debug#65]
手动点击展开左边全局变量(Globals)列表后，当切换到另一行断点或另一个co-routine的断点后, globals 列表就会关闭，还需手动点击展开才能看里面的内容．

而Locals 列表一旦展开或关闭后，能记住上次的状态而保持不变．能让globals 列表也能保持上次的状态吗？

**Comment by actboy168** [comment]
因为全局变量可能会很大，所以不会保持上一次的状态。影响这一行为的代码在此处，你可以自己修改来使用

https://github.com/actboy168/lua-debug/blob/e16519c621d271925e119757b4ec434ff1d1b378/extension/script/backend/worker/variables.lua#L789-L793

**Comment by Fedora7** [comment]
是把792这里改为 expensive = false 就可以保持上一次的状态，对吗？

**Comment by actboy168** [comment]
是
