### ISSUE TITLE
win10 x64下设置官方编译的lua.exe+lua.dll调试启动后就卡在不动。

### ISSUE THREAD

**Issue by jxlczjp77** [actboy168/lua-debug#66]

**Comment by actboy168** [comment]
请提供可复现的步骤

**Comment by jxlczjp77** [comment]
已经搞定了，不过要用这个配置
{
        "type": "lua",
        "request": "launch",
        "name": "Launch",
        "runtimeArgs": "${workspaceFolder}/test/test.lua",
        "cwd": "${workspaceFolder}",
        "runtimeExecutable": "E:/work/c++/vcpkg/installed/x64-windows/tools/lua/lua.exe"
}

之前卡住的配置是这个：
{
        "type": "lua",
        "request": "launch",
        "name": "Launch",
        "program": "${workspaceFolder}/test/ldbstorage_test.lua",
        "cwd": "${workspaceFolder}",
        "luaexe": "E:/work/c++/vcpkg/installed/x64-windows/tools/lua/lua.exe"
}
