### ISSUE TITLE
lua无法调试,每运行一次进程里便会多一个lua进程

### ISSUE THREAD

**Issue by yyzz990** [actboy168/lua-debug#68]
lua无法调试,每运行一次进程里便会多一个lua进程
也没任何异常显示

**Comment by actboy168** [comment]
你的调试配置是什么

**Comment by yyzz990** [comment]
> 你的调试配置是什么

配置是默认的
原来是好的，后来不知道是我装错了什么软件或者，装错了什么插件，就不行了
后面再重装vscode 重装vscode插件都不行了

**Comment by yyzz990** [comment]
奇怪，我在虚拟机(win10_64)上下一个vscode64位，打印hello world 也是不行，不过会弹出lua的控制台

**Comment by sei233** [comment]
同楼主问题，不过我是一下下来就不能调试，请问楼主解决了么？
