### ISSUE TITLE
thread doesn't disappear in vs code after receiving thread exited event

### ISSUE THREAD

**Issue by Fedora7** [actboy168/lua-debug#69]
backend 发出thread exited event，frontend 也转发给 vs code, 例如：
{"type":"event","event":"thread","body":{"reason":"exited","threadId":"122"},"seq":68}
at ...ctboy168.lua-debug-1.7.0/script/common/serverFactory.lua

但该thread 在vs code左栏显示一直显示存在，没有消失．所有threads 都是这个现象．
backend在stop 事件里发送的thread信息里也不再包括这些已exited 的thread, 但对vs code 的显示没有影响．

为了比对，用另一个支持debug 协议的客户端(https://github.com/puremourning/vimspector )调用frontend, backend 发送同样的thread exited event, 该thread 会在客户端(vim)的马上消失．以此看，可能是javascript里处理exited 事件的问题．

**Comment by actboy168** [comment]
我测试没有问题

**Comment by Fedora7** [comment]
能说一下你是如何测试的吗？例如测试时用的代码．以便比对是什么导致在我的vs code 不能正常在UI 更新thread 的显示．谢谢

**Comment by actboy168** [comment]
此前有问题ContinueResponse没有指定allThreadsContinued，会被VSCode视作重新激活了所有的thread。如果continue时有多个thread处于pause状态， 就会导致前端和后端的状态不一致。 

f013871116c90a8874cf999e0e12c7f3de2f56ae 你可以再试试是不是这个问题。
