### ISSUE TITLE
multi-lines variable value display in watch panel

### ISSUE THREAD

**Issue by Fedora7** [actboy168/lua-debug#70]
在左边watch 栏显示变量的值时，如果该值有多行例如json, 或text表格, 会显示成带有\n的单行信息，读起来很困难．当鼠标移到改值上面时，可以显示为多行的形式，但会被截断，内容稍微多的时候就看不到后面的内容了．请问这两处的相关代码在何处？能否在launch.json 添加配置选项，以便有机会选择不同的显示模式(单行，多行，显示最大字节数)．Thanks

**Comment by actboy168** [comment]
这个你需要去给VSCode提
