### ISSUE TITLE
多线程如何测试

### ISSUE THREAD

**Issue by qgx** [actboy168/lua-debug#71]
你好，新版本添加了thread ，请问如何触发 后端发送 thread exited 事件

**Comment by actboy168** [comment]
调试器的thread并不是指操作系统的线程，而是一个独立的lua_State。

**Comment by qgx** [comment]
请问有没有测试线程创建退出的demo参考一下，运行这个demo可以实现更新vscode上的线程显示，或者，可否提供一下插件和vscode通讯的log，带线程事件的那种，谢谢。

**Comment by actboy168** [comment]
attach的方式，给每一个lua_State都初始化一遍调试器即可。
launch script的方式，不会检测新的lua_State创建，你需要使用类似attach的方式，自己在新的lua_State初始化调试器。
launch process的方式，全自动，无需格外的设置。

最简单易得的多lua_State多thread调试，可以用[skynet](https://github.com/cloudwu/skynet)。用launch process的方式配置好skynet的exe和启动参数，就能看到效果。

**Comment by qgx** [comment]
谢谢回复，请问给每个lua_State初始化调试器，是调用那个函数？，是dbg:start吗。
launch process的方式,我在windows下启动一个普通脚本失败，
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch process",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "runtimeExecutable": "${workspaceFolder}/lua",
            "runtimeArgs": "${workspaceFolder}/a.lua",
            "consoleCoding": "utf8"
        }
    ]
}

---------------直接运行 ./lua a.lua 没问题

**Comment by actboy168** [comment]
填lua.exe不是lua
