### ISSUE TITLE
vscode调试时io.write()不起作用

### ISSUE THREAD

**Issue by pixel-songhao** [actboy168/lua-debug#72]
您好，我发现在vscode中进行调试的时候发现io.write("string")不起作用，无论是向文件中还是标准输出中写都不行。
![image](https://user-images.githubusercontent.com/52732956/61350386-f2e3f880-a899-11e9-843c-5048e26739a5.png)
但是直接使用lua的话是可以输出的。
![image](https://user-images.githubusercontent.com/52732956/61350543-76054e80-a89a-11e9-9fe0-7cbb0345b354.png)

**Comment by actboy168** [comment]
默认的情况下调试器会捕获io.write的输出到调试控制台，你可以通过launch.json来改并这个行为。

当调试器捕获io.write时，它只会遇到换行符时才会输出到调试控制台。
