### ISSUE TITLE
how can you control lua version used by the debugger

### ISSUE THREAD

**Issue by nukropina** [actboy168/lua-debug#74]

**Comment by actboy168** [comment]
You can add luaRuntime in launch.json, which can specify the lua version to use.

**Comment by nukropina** [comment]
Thank you, that work for 5.2-5.4 32 and 64 bit
5.1 32bit and 5.1 64bit do not work, vs code is stuck and program never starts

**Comment by actboy168** [comment]
Please provide the steps to reproduce.

**Comment by nukropina** [comment]
following configuration does not work:
	{
			"name": "un_learn",
			"type": "lua",
			"request": "launch",
			"stopOnEntry": false,
			"program": "${workspaceFolder}/un_learn.lua",
			"cwd": "${workspaceFolder}",
			"path": "${workspaceFolder}/?.lua",
			"arg": [],
			"consoleCoding": "utf8",
			"luaRuntime":"5.1 64bit"
		},
When you click on play (F5) VS code starts a debug session, but nothing happens, program never starts running.
If you comment out 			"luaRuntime":"5.1 64bit"
or specify 5.2/5.3/5.4  32bit/64bit program runs and debugger works as expected.
5.1 32bit does not work either 

VS Code:
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Lua Debug: 1.11.1
OSX: 10.14.6 (18G87)
