### ISSUE TITLE
支持Openresty调试吗？

### ISSUE THREAD

**Issue by AlexStacker** [actboy168/lua-debug#79]
现在调试用的是ZeroBrane，基于MobDebug的，来回切换vscode两个工具不方便。没有看到这方面的文档。

**Comment by actboy168** [comment]
不支持

**Comment by AlexStacker** [comment]
有计划支持吗？

**Comment by actboy168** [comment]
没有。这是lua的调试器，不会考虑兼容其它语言。

**Comment by AlexStacker** [comment]
Openresty 就是用lua. 目前调试比较麻烦。

**Comment by actboy168** [comment]
OpenResty使用的是luajit，并且还是luajit的一个方言

**Comment by actboy168** [comment]
Already supported.
