### ISSUE TITLE
lua5.1版本打断点没有任何效果，关闭进程后不能主动退出调试状态

### ISSUE THREAD

**Issue by yuchaoo** [actboy168/lua-debug#81]
我的配置如下：
{
            "name": "launch process",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "runtimeExecutable": "${workspaceFolder}/cog.exe",
            "runtimeArgs": "-workdir ${workspaceFolder}",
            "consoleCoding": "utf8",
            "luaVersion": "5.1",
            "path": "${workspaceFolder}/src/?.lua"
        }

在加载lua时trunk名称是“@”+文件路径，是符合lua符号规范的，请问以上问题是什么原因造成的

**Comment by actboy168** [comment]
关闭进程后不能主动退出调试状态应该和#82是一样的。

你的意思是除了断点以为的功能都是正常的?

**Comment by yuchaoo** [comment]
除了断点以外没发现有其他的问题，那个断点没有效果能否定位一下问题所在
