### ISSUE TITLE
“断点”功能对中文路径的显示问题。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [actboy168/lua-debug#83]
要调试的文件在中文目录中，断点中显示为乱码

![截图_1RCs9pm8Bg1m82wY](https://user-images.githubusercontent.com/10376283/71074877-08997900-21be-11ea-9d8c-57a62ee911bb.jpg)

**Comment by actboy168** [comment]
在launch.json中指定正确的sourceCoding

**Comment by wy16W2pIilK1xgqN** [comment]
文件中没有sourceCoding 选项。
指的是"consoleCoding“吗？
设定的是 utf8。
不过不改也没问题了，明明什么都没做。
打扰你了，抱歉。
