### ISSUE TITLE
需要明确的文档以及attach 的dll 加载入口

### ISSUE THREAD

**Issue by w4454962** [actboy168/lua-debug#85]
你这边没写文档 test里的有是n久以前的， 你天天更新 不写文档不写注释谁看得懂你的东西。 为此我付出了1个通宵 + 查了你n个版本的差距 + 一堆测试 都没解决我所遇到的问题， 还有 以前的debugger.dll 只需要加载就可以 现在你改了什么鬼东西 端口的接口去哪里了， 现在怎么变成pid了 pid是个什么东西 进程id？ luaapi又是什么东西 在弱类型的语言里 不写注释 写简写 谁知道是什么东西

**Comment by w4454962** [comment]
我找了个2 3年前的debugger.dll 加载后 可以正常断点 只是查询对象的时候 有问题 会在控制台中报错， 我再找了去年小汐编译的debugger.dll 里面的接口不一样 找不到本地源文件 无法验证断点 我重新编译了个新的 源码 依赖lua53.dll 不能用在 luacore.dll 的程序里 好吧 修改 之后 研究你的入口文件 调用通了 发现 端口的接口哪里去了。 游戏内阻塞了 但是没端口 没交互  再次重开就一直崩溃了， 我只是想用一下你的插件， 就这么折磨人的吗。

**Comment by w4454962** [comment]
另外 端口的接口从 listen 到 io 到 后面不知道什么东西  接口改那么多次从来也没有文档 或者一句说明  甚至你的 test里面 还有个 start_debug.lua   demo 还在 代码封装已经变得不知道成什么样了。

**Comment by w4454962** [comment]
不行 换luastudio  放弃你

**Comment by actboy168** [comment]
内部实现的代码没有注释很正常

**Comment by w4454962** [comment]
我只想知道你 原本attach的端口 现在改成什么接口了。

**Comment by actboy168** [comment]
我不明白”attach的端口“指的是什么

**Comment by w4454962** [comment]
18年 = dbg:listen(address .. ':' .. post)
19年 = dbg:io(address .. ':' .. post)
20年 = dbg:start(address .. ':' .. post) 然后你给start同时加了 path/tmp_进程id的参数

以前使用是 在vscode 中启动 attach模式的插件
先 local dbg = require 'debugger'
然后 监听
有的版本是 start 有的版本是wait
之后在vscode中得到反馈

崩溃问题大概可能是 用vc2017以上版本编译的 remotedebug.dll 被vc2013的 lua宿主所加载导致的崩溃

**Comment by w4454962** [comment]
所以有面临新的问题。 然而你用了很多c++17的语法 不可能在 vc2013重新编译remotedebug。。

**Comment by actboy168** [comment]
https://github.com/actboy168/lua-debug/blob/master/extension/package.json#L327

**Comment by w4454962** [comment]
不是这个问题 2020年 你把 io函数 换成 start 这里我看清楚了。  那么之后需要解决加载崩溃的问题

**Comment by w4454962** [comment]
算了 我还在自己看把
