### ISSUE TITLE
Freeze when run

### ISSUE THREAD

**Issue by playgithub** [actboy168/lua-debug#93]
Freeze when run with / without debugging.

![Screenshot_2020-05-19_22-10-29](https://user-images.githubusercontent.com/3665590/82339248-69a0d380-9a20-11ea-98b2-5130dc69c1d2.png)

test.lua:
```
print("hello")
```
---
Version Info
Lua: 5.3.5
Lua Debug: 1.23.6
VSCodium: 1.45.1 (VSCodium = vscode - telemetry)
OS: Manjaro x86_64

**Comment by actboy168** [comment]
You may need to recompile a binary.

https://github.com/actboy168/lua-debug/blob/master/extension/README.md

**Comment by playgithub** [comment]
luamake built successfully, I tried to follow the doc https://github.com/actboy168/lua-debug/blob/master/extension/README.md, but hard to understand it, some questions:
* How to install luamake
* Does it mean to install lua-debug through step 3 to 5 instead of through the plugin manager of vscode?

**Comment by actboy168** [comment]
> * How to install luamake?
Installing luamake means adding an alias for luamake in your shell.Of course, you can also use luamake without installation, for example `~/luamake/luamake`.

> * Does it mean to install lua-debug through step 3 to 5 instead of through the plugin manager of vscode?
Yes.

**Comment by playgithub** [comment]
Thanks
