### ISSUE TITLE
attach模式下 第一次能附加到进程，退出调试后，再次附加就不行了

### ISSUE THREAD

**Issue by AliserRe** [actboy168/lua-debug#95]
![image](https://user-images.githubusercontent.com/29608781/85881437-2bad8100-b810-11ea-875e-f28e6cbea8b8.png)

**Comment by sumneko** [comment]
加班到现在？这么辛苦

**Comment by AliserRe** [comment]
没有。。。就是突然想到了还有这个问题没解决，就问下。

**Comment by AliserRe** [comment]
小汐大佬知道咋回事不

**Comment by sumneko** [comment]
不知道，我这边用lsp测试也确实只能附加一次，第二次连上后会秒断开
