### ISSUE TITLE
Can not attach debuger to Unreal 4.25 with a LUA51 extension.

### ISSUE THREAD

**Issue by asomfai** [actboy168/lua-debug#96]
I've added a LUA5.1.5 plugin to UE4.25.
UE4Editor.exe loads the LUA dll: 
'UE4Editor.exe' (Win32): Loaded 'C:\Work\Work\unreal.lua\Plugins\Lua51\Binaries\Win64\UE4Editor-Lua51.dll'. Symbols loaded.
The LUA script are also working, but I need a good debugger.

But when I try to attach the lua-debugger to UE4 whit this launch.json:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "attach",
            "name": "Attach",
            "processName": "UE4Editor.exe",
            "stopOnEntry": true,
            "consoleCoding": "utf8",
        }
    ]
}

Then UE4 loads the launcger.x64.dll:

'UE4Editor.exe' (Win32): Loaded 'C:\Users\akos.somfai\.vscode\extensions\actboy168.lua-debug-1.24.0\bin\win\launcher.x64.dll'. Module was built without symbols.

But nothing happens after, execution will not stop at breakpoints, apparently the debugger fails to establish the connection to the exe.

I have tried it with an other, simpler X64 app, which also uses LUA 5.1.5 as DLL, in this case much more dll were loading when I attached the debugger to this exe, and the debugger was also working as it should:

'luabridge_test.exe' (Win32): Loaded 'C:\Users\akos.somfai\.vscode\extensions\actboy168.lua-debug-1.24.0\bin\win\launcher.x64.dll'. Module was built without symbols.
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Users\akos.somfai\.vscode\extensions\actboy168.lua-debug-1.24.0\runtime\win64\lua51\remotedebug.dll'. Module was built without symbols.
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. 
'luabridge_test.exe' (Win32): Loaded 'C:\Windows\System32\wshunix.dll'. 

Do you have any idea how can I fix this?

**Comment by actboy168** [comment]
I don't have UE4. Loading the debugger manually is better than automatically loading the compatibility.

e.g. https://github.com/sumneko/lua-language-server/blob/master/debugger.lua
