### ISSUE TITLE
Can not compile the plugin.

### ISSUE THREAD

**Issue by asomfai** [actboy168/lua-debug#97]
Hi there,

I am trying to compile lua-debug on Windows 10.
I've downloaded and compiled (with msvc_build.bat) the luamake repo, copied these files from luamake to lua-debug root:
bee.dll 
lua54.dll 
luamake.exe 

I have also installed the Tasks and extensionPath extensions too.

But when I open the lua-debug folder in Visual Studio Code, then hit the "Rebuild" button on the status bar, I get this error:
> Executing task: luamake remake <

luamake: cannot open J:\Work\lua-debug\main.lua: No such file or 
directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

There is a make.lua in lua-debug's root folder, but simply renaming it to main.lua will not work either.

What did I wrong?

**Comment by actboy168** [comment]
`luamake` is not just a binary file, so you cannot simply copy it.
