### ISSUE TITLE
Building lua-debug 64 bit

### ISSUE THREAD

**Issue by asomfai** [actboy168/lua-debug#98]
Hi there,

I try to compile lua-debug 64 bits on Windows.
I have to debug a 64 bit API which uses LUA as DLL. 
I've downloaded & compiled bee.lua and luamake, and I've added both tool's path to PATH environment variable. I've also added Tasks to VS code.
Now I can build lua-debug; but there are two problems.
First: it does not seem to build a 64 bit version; See: debugger.lua tries to load the remotedebug.dll from the win64 folder, but there is only a lua-debug\publish\runtime\win32 (and linux).
Second: there is an error message during Rebuild, it seems the copy command does not create the path if it does not exsist.
> Executing task: luamake remake <

[1/10] j:/Work/luamake/luamake.exe lua make/update_version.lua
[2/10] Lua def build/lua54/windeps/lua.def
[3/10] Lua import lib build/lua54/windeps/lua_x86.lib
   Creating library build/lua54/windeps/lua_x86.lib and object build/lua54/windeps/lua_x86.exp
[4/10] j:/Work/luamake/luamake.exe lua make/copy_extension.lua
FAILED: build/msvc/_/copy_extension
j:/Work/luamake/luamake.exe lua make/copy_extension.lua
j:/Work/luamake/luamake.exe: copy_file: The system cannot find the path specified.: "J:\Work\lua-debug\extension\script\dbg.lua", "J:\Work\lua-debug\publish\runtime\linux\lua51\dbg.lua"
stack traceback:
        [C]: in function 'bee.filesystem.copy_file'
        J:/Work/lua-debug/make/copy_extension.lua:29: in main chunk
        j:/Work/luamake/scripts/command/lua.lua:59: in main chunk
        j:/Work/luamake/scripts/util.lua:54: in function 'util.command'
        j:/Work/luamake/scripts/main.lua:6: in main chunk
        [C]: in function 'require'
        j:\Work\luamake\main.lua:5: in main chunk
        [C]: in ?

(This can be worked around by manually creating all missing folder.)

**Comment by actboy168** [comment]
You can use `luamake -arch x64` to compile the 64-bit lua-debug.
